### ISSUE TITLE
Header >> Padrão

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#1]
Header Padrão com opções específicas.

1. **Linha Verde** - parte de cima - Opções do Tema

- [x] A opção inicial é um seletor de região da Loja. O usuário precisará optar obrigatoriamente por alguma região (via CEP ou cadastro) para poder inserir algo no Carrinho.

- [x] Opções de Telefone e Whatsapp devem estar nas "Opções do Tema".

2. Campo de Busca Simples. Carrinho e Link para "Minha Conta"

3. Menu de Páginas do site (Nossa História, Blog)

4. Menu de Categorias da Loja

Com o menu aberto:

<img width="1273" alt="header - padrao - home a boa terra" src="https://cloud.githubusercontent.com/assets/5107285/13110156/5bd85acc-d565-11e5-880f-4d69b4b64c1e.png">

Com o carrinho aberto:

<img width="1018" alt="header - a boa terra 2" src="https://cloud.githubusercontent.com/assets/5107285/13110241/dfb6b74e-d565-11e5-8250-ca6a33c9c2f4.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Uma duvida que to me matando aqui pra descobrir: Qual a fonte disso? Não to conseguindo identificar pelo Photoshop :(

**Comment by diogosp** [comment]
[BELLABOO.zip](https://github.com/brasadesign/aboaterra-theme/files/141387/BELLABOO.zip)
Aqui a fonte. Agora que vi que nao subiu pro Drive

**Comment by matheusgimenez** [comment]
Essa é que está em vermelho não? (usada nos titulos e seções). To querendo saber da outra, usada em outros textos, como nesse box verde.

**Comment by diogosp** [comment]
Não é Trebuchet? me lembro dela falar isso.

**Comment by diogosp** [comment]
@matheusgimenez me avisa se deu certo. Caso não deu certo eu falo com a designer

**Comment by matheusgimenez** [comment]
É isso. Me enrolei na real, tava informando essa desde o inicio no Photoshop, mas não acreditei por ser uma fonte padrão. Achei que ele não tivesse conseguindo achar e trazendo uma parecida..

Valeu!

**Comment by matheusgimenez** [comment]
As imagens dentro dos dropdowns do menu são imagens de categoria de produto. Só vai aparecer imagem ali caso o item pai seja uma categoria de produto e claro, tenha imagem setada nele.

**Comment by diogosp** [comment]
@matheusgimenez meu olhar sobre o HEADER (Pente Fino e Responsivo):

- [ ] A Barra verde com o seletor de região deveria ficar fixa na rolagem da página. Isso vai ajudar o usuário a perceber a importância do seletor

- [ ] Quando eu mexo no tamanho da página o campo de PESQUISA encavala perto do LOGO

- [ ] O tamanho do Logo AUMENTA quando eu mexo na largura da janela. Poderia deixar ele sempre no mesmo tamanho do original. e conforme vai diminuindo a janela deixar ele centralizado também.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro e @matheusgimenez eu vi um pequeno "problema" adicional que queria ver com voces como poderiamos resolver. O Box do carrinho que abre quando clicamos no icone apresenta tambem os produtos dentro das cestas, isso pode confundir o cliente e virar um problemao quando o cliente faz a compra de uma cesta que possui 10 produtos (o que pode acontecer).

Vejam se conseguem encontrar uma solucao:

![image](https://cloud.githubusercontent.com/assets/5949986/15232625/3a0b5f5c-1868-11e6-8498-8b35fd2de743.png)

**Comment by matheusgimenez** [comment]
@LuwkasLima qual sua solução pra isso? exibir somente a cesta pai?

**Comment by LuwkasLima** [comment]
Isso!

**Comment by LuwkasLima** [comment]
Deixa eu responder direito...

Eu nao quis dar uma proposta, porque acho que voces precisam buscar uma alternativa limpa e nao fazer qualquer coisa pra atingir a minha sugestao. Mas pelo que me parece, a unica solucao inteligente (do ponto de vista Funcional - do Cliente) eh deixar somente a Cesta. Assim evitamos problemas, caso a Cesta contenha 50 produtos diferentes...

**Comment by matheusgimenez** [comment]
Resolvi o ponto de exibir somente a CESTA.

**Comment by matheusgimenez** [comment]
Resolvido tarefas de responsivo no header.

**Comment by LuwkasLima** [comment]
Item 1 ainda esta em aberto, vou validar com o Cliente este Drop-box após a promoção da versão Beta para produção...

**Comment by LuwkasLima** [comment]
@diogosp vou deixar isso contigo tbm, nao acho que precisa ser visto com urgencia...

**Comment by diogosp** [comment]
@matheusgimenez nas imagens que aparecem no MENU (veja abaixo)

![2016-08-09_14h46_25](https://cloud.githubusercontent.com/assets/5107285/17527009/105910c8-5e40-11e6-8886-003b80b5e99a.png)

Não existe opção pra DEIXAR EM BRANCO? tipo, por agora aparece um quadrado preto, parece que está faltando algo. e na real eles querem deixar em alguns períodos sem esta imagem

**Comment by isaquemelo** [comment]
@diogosp vê isso com o @matheusgimenez não sei bem como esse negocio da img funciona...

**Comment by diogosp** [comment]
@matheusgimenez nos explique como este quadro funciona. Se ficar sem imagem destacada este quadro fica horrível no layout.

**Comment by isaquemelo** [comment]
Aguardando.

**Comment by diogosp** [comment]
@isaquemelo o Matheus ajeitou. era coisa de configuração

**Comment by isaquemelo** [comment]
Ótimo.

**Comment by diogosp** [comment]
@matheusgimenez temos um problema aqui (que eu já havia chamado sua atenção na sexta):
Quando o cliente adiciona qq item ao CART **DEVERIA** atualizar o carrinho no Header (ele estava atualizando normalmente e no demo do Storefront faz isto normalmente). Nem no DEV está rolando agora.
Isto é ao Adicionar algo no carrinho o cliente já deveria ver a atualização dos valores e finalizar a compra. Do jeito que está o cliente precisa dar um refresh manual pra atualizar o CART ali no Header.

eu testei neste demo aqui e funfou
http://demo.woothemes.com/storefront/product-category/clothing/

E lembro que isto funcionava normalmente, foi numa das últimas mudanças que ocorreu isto.

PASSOS PRA REPRODUZIR:
- testei dos dois jeitos - logado com admin ou passando CEP Válido
- Testei inserir em 3 lugares diferentes: Home, Categoria e Diretamente no post do Produto. O Único modo que funciona é o direto na página do produto - que não só atualiza como mostra um INFO tb pra ir pro Carrinho. - E ele atualiza o Header automaticamente.

![selection_001](https://cloud.githubusercontent.com/assets/5107285/18631731/151851b2-7e4a-11e6-9b75-34fbf41d019d.png)

**Comment by diogosp** [comment]
@isaquemelo 
Na barra verde no topo:

- fonte normal (romana) e a palavra log in e São Paulo é para ser em bold.
- Colocar trebuchet na fonte do telefone
