### ISSUE TITLE
Loja >> Vendas por região - preços e entrega - 3 regiões

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#11]
A loja terá como base 3 regiões que impactam tanto no preço de cada produto quanto no valor da entrega deles.

O usuário precisará escolher a região de entrega (1 é SP, outras duas são interior) através do CEP.

Os produtos deverão aparecer com o preço e valor de entrega de acordo com sua região.

Cada região possui um circuito de entrega dos produtos diferente (cada dia da semana é uma região de entrega).

**Comment by matheusgimenez** [comment]
A escolha vai ser através de CEP mesmo?

Na minha concepção seria um option simples com a escolha da região.

**Comment by matheusgimenez** [comment]
Veja os pontos que anotei desse sistema, vamos debatendo pra ver o que devo mudar e o que continua da minha ideia:

- Criar uma opção no painel para o cadastro de cada cidade, sendo uma sintaxe com: Nome da cidade: Sigla(exemplo, São Paulo:SP);
- Criar variações de cada produto utilizando a sigla da cidade;
- A cidade escolhida ficará salva como usermeta, ou seja, o usuário terá que se registrar para selecionar.

**Comment by diogosp** [comment]
@matheusgimenez acho que a única maneira de termos a CIDADE como parte do cadastro é se conseguissemos filtrar por BAIRRO tb. Pq acredito que em SP terá divisões de dias de entrega por região dentro da cidade entendeu?

**Comment by matheusgimenez** [comment]
Sim, poderiamos, se no option houvesse:

Sao Paulo - Cidade Tiradentes: sp_tiradentes
Sao Paulo - Tucuruvi: sp_tucuruvi;

No seletor ficaria um select com:

Sao Paulo - Cidade Tiradentes;
Sao Paulo - Tucuruvi

**Comment by diogosp** [comment]
@matheusgimenez eu queria entender melhor esta mecânica da coisa. Na minha visão já havia uma ferramenta automatizada onde se converteria o CEP do BR em Bairro/Cidade quando necessário.

Agora, não sei se dá pra "agrupar" conjuntos de CEP/Bairros pra gerar esta "Região 1", "Região 2" etc. Eu tava entendendo que talvez este seria o escopo do DEV.

Eu tava entendendo que deveria funcionar como a questão da variação de valor de entrega de FRETE por CEP. Como funciona este plugin no Woo? Ele não puxa um valor X de entrega de acordo com alguma config interna?

Claro, isso precisa ser pensado sobre como isso se altera conforme o passar do tempo e como o ADMIN irá controlar as regiões futuramente.

no PRODUTO eu acho que deveria marcar somente "A Região 1", não o CEP ou Cidade, pq geraria uma confusão danada.

Há alguma saída pra isso?

**Comment by diogosp** [comment]
**SOLUÇÕES CEP**

Aqui exemplo pra puxar endereço/bairro/cidade quando preenche CEP

http://www.pinceladasdaweb.com.br/blog/2012/01/31/webservice-consulta-de-cep-diretamente-ao-site-dos-correios/

Aqui outra iniciativa bem bacana
https://viacep.com.br/

Aqui outro (com base desatualizada)
http://www.byjg.com.br/site/xmlnuke.php?lang=pt-br&xml=onlinecep

**Comment by diogosp** [comment]
**SOLUÇÕES REGIÃO**

Plugin do Woo que cria preços por região pra cada produto. (com possibilidade de variações de moeda etc que não precisamos).
https://wordpress.org/plugins/flat-rate-per-countryregion-for-woocommerce/

Aqui outro
https://wordpress.org/plugins/woocommerce-product-price-based-on-countries/screenshots/

Aqui um outro tipo de saída que tem várias opções legais. Que é exatamente o que estamos procurando.
https://www.woothemes.com/products/catalog-visibility-options/?ref=2
https://chrislema.com/woocommerce-product-pricing/

**Acredite** teve gente que usou o Multi Language pra setar estas diferentes informações de região (o que pode ser uma saída simpllificada mesmo)
[Solução via Multi Language](http://wpml.org/documentation/related-projects/woocommerce-multilingual/multi-currency-support-woocommerce/)

**Comment by diogosp** [comment]
@matheusgimenez 
Conforme conversamos a melhor saída é puxar por CEP.
Nesta ferramenta dos Correios puxa por Faixas de CEP conforme você indica a cidade

http://www.buscacep.correios.com.br/servicos/dnec/menuAction.do?Metodo=menuFaixaCep

Para SP precisamos puxar por BAIRRO tb.

---
Usaremos o plugin para criar as regiões como base (no exemplo estão países), no nosso caso precisaremos cadastrar as faixas de CEP (que podem ser várias) pra cada região: https://wordpress.org/plugins/woocommerce-product-price-based-on-countries/screenshots/

Lembrando que as regiões serão criadas para:
- diferenciar preços de produtos
- diferenciar preços de entrega
- avisar pro usuário qual o dia da semana de entrega.


Achei as regras de como eles criam os CEPs no Brasil:

1XXXX: Região 1 - "litoral e interior de São Paulo"
13XXX: Sub-Região 13 - "regiões do interior de São Paulo"
130XX: Setor 130 - "Região de Campinas"
1303X: Subsetor 1303 - "Região Sul de Campinas" (São Bernardo, Vila Industrial, Parque Industrial, etc.);
13035: Divisor de subsetor 13035 - "Vila Industrial".
-680: Sufixo de distribuição 680 - atribuição arbitrária à Avenida João Jorge, dentro do 13035.

**Comment by diogosp** [comment]
@matheusgimenez ainda estou procurando as divisões por bairro em CEP. Me cobre isso depois.

**Comment by diogosp** [comment]
@matheusgimenez consegui uma lista em HTML que dá pra tentar raspar o dado.

http://www.brasilao.com/cep/sao-paulo/

**Comment by diogosp** [comment]
@matheusgimenez **ACHEI**

Faixas de CEP de SP Capital e região metropolitana.

https://docs.google.com/spreadsheets/d/1-UvT7vNBqutzPfpzVuJ3-oRcGIDawedUNhTIYCfoaeY/edit#gid=0

**Comment by diogosp** [comment]
@matheusgimenez  novas descobertas.

Há um plugin que faz aparecer preços diferentes pra diferentes User Roles. Isto seria interessante e bastante simples de implementar. Ele já separa por Grupos de Usuários. Já mascara os preços caso o usuário esteja sem registro no site tb.

Eu to colocando aqui como uma ideia, não é pra comprarmos o plugin. É pra acharmos variações de possibilidades.

http://codecanyon.net/item/woocommerce-prices-by-user-role/8562616
