### ISSUE TITLE
Loja >> Recuperar URLs da loja antiga e redirecionar pra nova

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#12]
Depois da loja já operando é preciso pegar as URLs da loja antiga e redirecionar pra nova.

http://www.aboaterra.com.br/cestas-organicas.php
http://www.aboaterra.com.br/p.php?c=44&Frutas
http://www.aboaterra.com.br/p.php?c=1&Legumes
http://www.aboaterra.com.br/p.php?c=2&Verduras

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima Este era um pedido do cliente pro novo site. Ele precisa que as URLs antigas (estas 4 aí) redirecionem pras novas páginas do WP. Lembro que vc falou que era coisa de inserir um PLUGIN pra isso.

**Comment by matheusgimenez** [comment]
Feito.

Página do plugin:

http://108.167.132.55/~aboat918/wp-admin/options-general.php?page=seo-redirection.php

Um exemplo funcionando:
http://108.167.132.55/~aboat918/p.php?c=2&Verduras

**Comment by diogosp** [comment]
@matheusgimenez Matheus isto estar ativo agora não atrapalhada.nada ne?

**Comment by matheusgimenez** [comment]
@diogosp não, não atrapalha

**Comment by diogosp** [comment]
@LuwkasLima vc em algum outro lugar apontou que já fez isso de redirecionar. Pode explicar melhor pra não confundirmos isso?
