### ISSUE TITLE
Loja >> Exportar TXT com códigos dos produtos e vendas

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#14]
A loja precisa exportar um arquivo de vendas pra dar baixa no estoque que é um sistema offline deles.

É preciso integrar o código do produto (deste sistema offline) e exportar da maneira correta.

**Comment by diogosp** [comment]
@matheusgimenez segue o arquivo que precisa exportar em cada venda. Vou colocar umas telas que ele fez lá do sistema offline deles. Lembrando:

1 - Exportar TXT com código do produto e quantidade de venda.
2 - Só salvar localmente na máquina do ADMIN. Eles fazem a importação no outro sistema manualmente. Deixar o próprio cliente nomear o arquivo ao salvar (mas sei lá de repente deixar como padrão o número da compra).

[CAPTURADO_MODELO BRASA.txt](https://github.com/brasadesign/aboaterra-theme/files/232431/CAPTURADO_MODELO.BRASA.txt)

**Comment by diogosp** [comment]
Print de como é o sisteminha atual
![loja boa terra - print atual](https://cloud.githubusercontent.com/assets/5107285/14752252/9c0ac964-08a4-11e6-805b-d8d85a95971c.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez so pra registar, acordamos que vai ter um botao na pagina de pedidos pra "Exportar Arquivo TXT":

![image](https://cloud.githubusercontent.com/assets/5949986/15257895/388a21ee-190e-11e6-9062-823299e2e713.png)

Assim o cliente pode exportar o arquivo que saira no seguinte formato:

![image](https://cloud.githubusercontent.com/assets/5949986/15257939/7d66a562-190e-11e6-996f-9b996938912e.png)

SKU = Numero do Produto
QTD = Quantidade

**Comment by matheusgimenez** [comment]
Feito. Para gerar o arquivo TXT é só ir na página de pedidos do dashboard e clicar no botao de download.

Avisando: somente os produtos com SKU serão exibidos na lista do TXT, lembrem de setar antes de testar, ok?

**Comment by LuwkasLima** [comment]
@matheusgimenez fiz o teste e esta muito bem feito, parabens cara!

So estou com duvida em um cenario e mandei e-mail para o cliente. Assim que ele responder te confirmo se precisamos fazer modificacoes ou nao.

At.,

**Comment by LuwkasLima** [comment]
@matheusgimenez o cliente nos confirmou que ele cadastra CESTAS como produtos dentro do sistema de estoque interno e portanto cada Cesta tera seu SKU e somente ele deve estar contido no TXT que exportamos (nao deve aparecer os SKUs dos produtos internos da Cesta).

Dessa forma, precisamos que voce faca essa alteracao para desconsiderar os SKUs dos produtos internos da Cesta e somente exportar o SKU da Cesta.

**Comment by matheusgimenez** [comment]
Feito.

Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou perfeito mano! Meu parabéns!!...

Só vai ficar uma correção pra ser feita na pr[oxima versão do site (criei uma label pra nos ajudar com isso "Pente Fino Necessario"). Precizamos mudar o que está escrito no box:

![image](https://cloud.githubusercontent.com/assets/5949986/15403237/a256c344-1dbd-11e6-90c7-e189cd1f5d09.png)

"Exportar Arquivo TXT"
