### ISSUE TITLE
[Prioridade 1] HOME >> Lightbox pra cadastro/login/CEP 

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#17]
A Loja estará dividida em 3 regiões (inicialmente).
O usuário precisa entender rapidamente quais são as regiões de entrega pra que ele não perca tempo montando o carrinho e só no final descobrir que não conseguirá concluir.

Pra isso eles entenderam que a melhor opção é:
- [x] Apresentar os preços de SP como padrão quando entra na loja
- [x] Quando o cliente tenta inserir um primeiro produto no Carrinho abre o lightbox pro cliente fazer a opção da região, se cadastrar ou fazer login

**Comment by matheusgimenez** [comment]
@LuwkasLima Não temos um layout disso né? Ou temos? me explica se devo fazer essa issue agora ou não.

**Comment by LuwkasLima** [comment]
@matheusgimenez nao tem mesmo, verifiquei aqui...mas entendo que podemos apresentar a seguinte pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/15333302/b9449134-1c2e-11e6-96bf-44a26bc7c1d4.png)


Link: https://drive.google.com/drive/folders/0B8Nss0g77Q6cbW56TG9rX2FMYzA

**Comment by LuwkasLima** [comment]
Espera, vi aqui que nao tem tudo o que o @diogosp esta apontando. Acho que sem layout fica complicado, deixa isso no gelo que eu resolvo.

**Comment by LuwkasLima** [comment]
@matheusgimenez explicando aqui, pois este issue sera nossa prioridade 1 da Semana.

Como deve funcionar?

1 - O Cliente entra pela PRIMEIRA vez no site (nao esta logado obviamente) 
2 - Ao navegar ele decide comprar um produto e clica em "Adicionar no Carrinho"
3 - O sistema deve abrir um Lightbox com a pagina de Cadastro/Login abaixo:

![image](https://cloud.githubusercontent.com/assets/5949986/15486899/7cd08412-210e-11e6-9ffd-66337efdf693.png)

Link: https://drive.google.com/drive/folders/0B8Nss0g77Q6cbW56TG9rX2FMYzA

4 - O cliente tem as seguintes opcoes agora:
   **A - Fazer o Login**

![image](https://cloud.githubusercontent.com/assets/5949986/15486961/fbbb3484-210e-11e6-8303-bbb80b98ff45.png)

   **B - Se Cadastrar**

![image](https://cloud.githubusercontent.com/assets/5949986/15486965/09c28302-210f-11e6-81d5-e0eae3e23120.png)


   **C - Checar se o seu CEP eh atendido pelo Sitio:**

![image](https://cloud.githubusercontent.com/assets/5949986/15486972/1cc40444-210f-11e6-824e-973d68440a18.png)

5 - Se o cliente, por ventura, clicar fora do lightbox e fecha-lo sem se cadastrar, o proximo produto que ele tentar incluir vai apresentar o lightbox mais uma vez. Caso ele tente avancar no carrinho, o mesmo mecanismo deve ser acionado ateh que ele entenda que precisa se logar pra finalizar a compra.

**Comment by matheusgimenez** [comment]
Feito. É a página de login padrão do woocommerce.

Segue o link em dev:  ( Testem deslogados, pode ser pela navegacao privada do browser )

http://dev.brasa.art.br/aboaterra/minha-conta

**Comment by diogosp** [comment]
@matheusgimenez como ficou isto aqui? to testando no DEV e não tem nada.

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima 

- [ ] Inserir o modal de login/cadastro na Barra Superior

- [ ] Inserir o modal de login/cadastro em TODOS os botões de inserir no carrinho na HOME e em qualquer página de produto e categoria. Pro cliente ser obrigado a logar desde o início. @matheusgimenez **precisamos que isto esteja implementado em qq produto desde que o usuário já não esteja logado. Pra que ele não lote o carrinho e só depois veja que não entrega na sua região**

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
@diogosp ainda existe uma possibilidade de furo (devem haver mais, mas esta eh a mais forte). Assim que vc entra e clica no carrinho, o Modal eh aberto e se vc nao tem conta e cria uma, ele te leva pra pagina MINHA CONTA ao invez de levar para a pagina de EDICAO da CONTA. Dai o que acontece? Se a pessoa nao preencher os dados de ENTREGA e ao invez, clicar pra voltar pra HOME, ele vai estar LOGADO e vai continuar vendo os precos de SAMPA (ou seja, nao os precos com base no CEP dele).

MInha sugestao eh que apos o cadastro o usuario seja levado a pagina de EDICAO DE CONTA, assim ele entende que precisa atualizar os dados dele e que o ENDERECO DE COBRANCA seja Obrigatorio de preencher.

Entende?

**Comment by diogosp** [comment]
@matheusgimenez e @LuwkasLima 
decisões com o cliente do **MODAL finalizado será assim:**

- [ ] Login do Usuário. Cliente se loga. O produto é inserido no carrinho e o usuário retorna pra página onde estava

- [ ] Cadastro do cliente: agora com 3 campos obrigatórios. Nome, E-mail e CEP.

- [ ] Retirar o Ajax de resultado NEGATIVO do CEP. Ele quer que caia DIRETO na "Página de Regiões Atendidas" e o texto pra explicar pro usuário testar outro CEP.

- [ ] Só aparecer o AJAX em caso de CEP POSITIVO. Com a mensagem ÚNICA pra todas as regiões.. E voltando pra URL onde o cliente estava, com o produto inserido no carrinho.

**Mensagem personalizada por região se MANTÉM:**

- [ ]  Colocar a mensagem do dia de entrega no checkout junto com o RESUMO DO PEDIDO abaixo do frete.

- [ ] Lembrar que no checkout re-confirmar o CEP de entrega e aparecer os ajax verde e vermelho caso não seja atendido.

![modal - login e cep - a boa terra](https://cloud.githubusercontent.com/assets/5107285/16805962/f1a59cc6-48e8-11e6-9cbf-0fadb226fd39.jpg)

**Comment by diogosp** [comment]
@matheusgimenez temos que avançar nisso aqui.

**Comment by LuwkasLima** [comment]
@matheusgimenez e @diogosp 

Fiz um teste negativo aqui e deu merda, detalhes:

1 - Entrei sem logar no site
2 - Adicionei um produto no carrinho e o Modal Abriu
3 - Fiz login, mas coloquei a senha errada
4 - [PROBLEMA] O modal saiu, o produto foi incluido no carrinho e somente quando eu fui pro carrinho eh que a mensagem de erro da senha apareceu:

![image](https://cloud.githubusercontent.com/assets/5949986/17147717/8ef09aea-5329-11e6-8656-5c7d8a51cff8.png)

O que es esperado?

Que o Modal continue e que a msg de erro de senha apareca no modal, para que o cliente faca login novamente.

**Comment by matheusgimenez** [comment]
Modal funcionando.

Quanto ao erro do login. Qual seria a ideia? quando der erro mandar pra página minha conta sem modal talvez? Lembrem que o WC nao tem ajax pra isso, não quero criar mais trabalho.

**Comment by diogosp** [comment]
@matheusgimenez pontualmente sobre o erro. se der erro de LOGIN ou SENHA. qual é a maneira mais fácil no WP? não dá pra dar erro e manter o modal sem logar? senão deixa ir pra tela de MINHA CONTA mesmo, só não deixe mesmo ele continuar o processo de colocar o carrinho.

**Comment by diogosp** [comment]
sobre o MODAL, alguns erros @matheusgimenez :

- Quando digita CEP inválido e redireciona pra Page Região Atendida. O sistema está incluindo o produto no carrinho de qq maneira. CORRIGIR.
- Não está atualizando os Preços/região e barra superior quando o CEP válido é inserido.

Sobre os textos do MODAL:

- Precisa ter os 3 campos: e-mail, nome e CEP.
- Nestes 3 campos precisam ser obrigatórios, com *.

**Comment by matheusgimenez** [comment]
Página de regiões criada:

http://dev.brasa.art.br/aboaterra/regioes-atendidas/

**Comment by matheusgimenez** [comment]
Sobre erro no login:

O caminho mais simples seria mandar pra página minha-conta.

**Comment by matheusgimenez** [comment]
> Não está atualizando os Preços/região e barra superior quando o CEP válido é inserido.

Isso acontece só quando o cara está logado, eu de fato não estou setando o CEP nesse caso, deveria?

> Quando digita CEP inválido e redireciona pra Page Região Atendida. O sistema está incluindo o produto no carrinho de qq maneira. CORRIGIR.

Corrigido.

> Precisa ter os 3 campos: e-mail, nome e CEP.

De fato esse 2 campos estão inuteis, já que não existe o registro nesse momento.

**Comment by matheusgimenez** [comment]
@matheusgimenez Resolvi o erro na hora de setar o CEP, agora está ok.

**Comment by matheusgimenez** [comment]
@matheusgimenez Pra fechar isso, precisamos ver dois pontos: os campos de email e senha que estão inuteis e pra onde o login fail deve mandar

**Comment by diogosp** [comment]
@matheusgimenez seus dois pontos:

- [ ] sobre os campos inúteis. não há o que fazer mesmo? guardar na memória caso o cliente queira concluir o cadastro posteriormente? Se não houver outra solução deixa os campos ali na interface sim caindo em lugar nenhum.

- [ ] login fail: manda pra tela de MINHA CONTA. Lembra de não adicionar o produto no carrinho

**Comment by diogosp** [comment]
@matheusgimenez no PERSONALIZAR
Precisa retirar a opção do Customizer - 1º campo - **"Mensagem de endereço não atendido (erro)"**

esta mensagem não será mais usada. não aparecerá erro. só redirecionamento

**Comment by diogosp** [comment]
@matheusgimenez o cliente quer os campos de NOME e E-MAIL pra ficar como obrigatórios (mesmo que não vá pra lugar nenhuma). 
Na produção não está aparecendo NOME nos campos. Só email e CEP.

**Comment by diogosp** [comment]
@matheusgimenez mais erros:

- [ ] Falta colocar Nome e EMAIL como obrigatório (comentário anterior)
- [ ] Quando abro o produtor SINGLE ele está deixando colocar no Carrinho de qq maneira. Precisa bloquear de todos os métodos.
- [ ] Página regiões atendidas EM PRODUçÂO subiu com erros: 1- Botão testar outro CEP vai pra Página MINHA CONTA. 2 - ÁREA DAS REGIÕES ESTÁ SEM O TÍTULO DA PÁGINA (NO DEV FUNCIONA)

![2016-08-09_15h14_13](https://cloud.githubusercontent.com/assets/5107285/17528068/30de6498-5e44-11e6-8659-57509069d882.png)

**Comment by matheusgimenez** [comment]
Todos pontos feitos!

Sobre o titulo da página regiões atendidas:

Você precisa colocar ele manualmente pelo editor, como um elemento cabeçalho 1, 2 ou 3. No caso, deixei o 3 em produção.

**Comment by diogosp** [comment]
@matheusgimenez faltou colocar o CAMPO **NOME** também, e manter como obrigatório como o e-mail

**Comment by diogosp** [comment]
@matheusgimenez no MODAL o campo "Recuperar Senha" não ta funcionando. Não tem ação nenhuma nele.

**Comment by diogosp** [comment]
@isaquemelo o MODAL precisa de um pente fino de CSS.
Ele está todo desalinhado. [Na página MINHA CONTA ele puxa corretamente, veja lá](https://aboaterra.com.br/minha-conta/)

![selection_005](https://cloud.githubusercontent.com/assets/5107285/18632395/9d9e9c3c-7e4d-11e6-965e-4187f9a00ffb.png)

**Comment by diogosp** [comment]
@isaquemelo eles pediram mais uma olhada neste modal. Só pra arrumar uns detalhes. 
![modal-modificacoes](https://cloud.githubusercontent.com/assets/5107285/18762809/d70a6a38-80e0-11e6-8ae9-0e1342e162c6.png)

**Comment by diogosp** [comment]
@matheusgimenez precisamos ajeitar isto aqui

- **Depois que insere o CEP e dá POSITIVO - Aparece o Botão FECHAR. trocar pra OK**
- **Algum problema em alguns usuários não aparece o botão FECHAR. Talvez precisemos checar o CSS pra ver isso**

<img width="1339" alt="a_boa_terra_ _organicos" src="https://cloud.githubusercontent.com/assets/5107285/19537345/58ac5634-962e-11e6-94d3-041fa750144d.png">

- **se não preenche NENHUM CEP ele dá mensagem de que entrega**
<img width="1329" alt="banners_and_alerts_and_a_boa_terra_ _organicos" src="https://cloud.githubusercontent.com/assets/5107285/19537148/b234ecb2-962d-11e6-88aa-9cb277876f06.png">

**Comment by matheusgimenez** [comment]
Remover possibilidade de enviar vazio: FEITO;

**Comment by matheusgimenez** [comment]
Trocar botão fechar por "OK": Feito;

**Comment by diogosp** [comment]
@matheusgimenez 
Precisamos forçar que o MODAL abra mesmo se o cliente for pra URL direto.
O modal não está aparecendo quando o cliente clica aqui: https://aboaterra.com.br/minha-conta
O modal precisa abrir em 100% das vezes pra evitar aquele erro de não aparecer o botão FECHAR.

**Comment by matheusgimenez** [comment]
Resolvido:

http://dev.brasa.art.br/aboaterra/logar-modal/

**Comment by LuwkasLima** [comment]
@matheusgimenez como fazemos pro link "Minha Conta" comecar a abrir no Modal entao, ao invez de pagina comoo esta hoje?

![image](https://cloud.githubusercontent.com/assets/5949986/23185927/c9708790-f84a-11e6-9625-3274a5a08713.png)

**Comment by diogosp** [comment]
@matheusgimenez a questão aqui não foi resolvida.
a URL https://aboaterra.com.br/minha-conta/ quando clicada onde o @LuwkasLima apontou não abre via MODAL. abre a página normalmente. E isto é um erro. É obrigatório através desta URL abrir via MODAL para evitar com que o usuário fique sem as mensagens de que o CEP não é válido.

**Comment by diogosp** [comment]
Ativei o Reveal Modal na página (pq acho que o @matheusgimenez só tinha atualizado na url -modal). Tudo resolvido. Modal ta aparecendo diretamente quando clica na URL.

RESOLVIDO
