### ISSUE TITLE
Página do Produto >> Imagem do Produto - com e sem zoom - Mouse Over

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#19]
Na página do produto teremos as imagens dos produtos que reagem com mouse over.

Sem zoom
<img width="365" alt="screen shot 2016-03-08 at 16 46 21" src="https://cloud.githubusercontent.com/assets/5107285/13614022/52b5697e-e54d-11e5-8948-8cabfa29b47d.png">

com zoom quando passa o mouse
<img width="332" alt="screen shot 2016-03-08 at 16 47 51" src="https://cloud.githubusercontent.com/assets/5107285/13614082/8ee98646-e54d-11e5-8bce-09468560c808.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdHNlYUp3MVJiZUE

**Comment by diogosp** [comment]
Pente Fino CSS

Remover quadro cinza da Imagem do produto

**Comment by isaquemelo** [comment]
Define melhor essa issue por favor @diogosp =)

**Comment by diogosp** [comment]
@isaquemelo acho que vc resolveu. a imagem do produto estava com um 2º quadro cinza dentro dela. Estava poluindo demais (a pedidos da designer)

<img width="603" alt="farinhas_ _a_boa_terra" src="https://cloud.githubusercontent.com/assets/5107285/18070820/f2698998-6e26-11e6-9f38-c6a986a49e2e.png">

**Comment by diogosp** [comment]
@isaquemelo a questão é que estavam dois quadros cinzas na imagem destacada do produto. vc deve ter arrumado.
