### ISSUE TITLE
Footer >> Padrão

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#2]
Footer da Home

1. Logo "A Boa Terra" - Acima e Centralizado

2.  - Lado Esquerdo - **Formas de Pagamento** Opções de seleção de ícones via **"Opções do Tema"**

3. - **Centro** - Menus de Rodapé do Wordpress e Ícones de Redes Sociais - via "Opções do Tema".

4. - Lado Direito - **Assine nossa Newsletter** - via plugin MDirector - http://www.mdirector.com.br/integracoes/wordpress/ 

<img width="304" alt="footer - a boa terra" src="https://cloud.githubusercontent.com/assets/5107285/13089521/3217294e-d4d8-11e5-8b8a-34422d99037b.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Feito

**Comment by diogosp** [comment]
Ficou bom. Só acho que como está tudo escrito em BRANCO seria melhor dar um espaçamento melhor quando muda o tamanho da janela pra não ficar tão confuso. Mas é mínimo. @matheusgimenez

**Comment by LuwkasLima** [comment]
@matheusgimenez e @isaquebrasileiro precisamos do seguinte aqui:

1 - Logo da Boa Terra no centro
2 - Espaçamento em baixo dos elementos e entre eles maior.

![image](https://cloud.githubusercontent.com/assets/5949986/15194655/9671af7e-1789-11e6-8fe2-f8908909fb9c.png)

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by LuwkasLima** [comment]
A proposito, os PSDs estao na pasta do projeto! Utilizem eles...

**Comment by matheusgimenez** [comment]
O ponto 1 eu esqueci de setar a imagem, me desculpem.

É um customizer option, eu já fiz, só esqueci de setar no dev :(

Feito agora.

Os outros pontos preciso entender melhor @LuwkasLima

**Comment by LuwkasLima** [comment]
Oi Matheus, segue..

2 - Me refiro aos espaco entre os elementos mesmo, talvez Margin ou Padding...

**Comment by matheusgimenez** [comment]
Mas você pretende mais espaço ou menos?

**Comment by matheusgimenez** [comment]
Feito, esperando resposta do @LuwkasLima

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou certo. Só o logo que está um pouco maior do que o proposto no Layout, mas eu gostei assim. Vou deixar pra revisão de Pente-Fino, ok?

**Comment by diogosp** [comment]
Pente fino CSS necessário

- tudo enorme.
- campos desconfigurando pq as fontes estão grandes (ver TELEFONES)
- Laranja do botão Newsletter está diferente do restante do site

**Comment by diogosp** [comment]
Retiramos o Widget da Newsletter do Footer da HOME.
Eles pediram pra Centralizar todo o Footer pq fica estranho assim. 

![selection_019](https://cloud.githubusercontent.com/assets/5107285/18687465/a079dcbe-7f56-11e6-88fc-04393fcff9b8.png)

**Comment by isaquemelo** [comment]
Pronto.

**Comment by isaquemelo** [comment]
No DEV.
