### ISSUE TITLE
Página do Produto >> Valor do produto - Descrição e adicionar no carrinho

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#20]
Ao lado das imagens do produto.
Há um erro no layout completo. Não é pra deixar o botão "Finalizar compra" E está faltando um campo descrição do produto.

<img width="147" alt="screen shot 2016-03-08 at 16 49 45" src="https://cloud.githubusercontent.com/assets/5107285/13614152/da913c9c-e54d-11e5-8995-407c37d3e4f8.png">

Um Adendo: cada produto precisará ter um campo de Código de Produto que o Administrador da loja precisará cadastrar manualmente para que ao exportar as vendas bata direto com o controle interno deles de estoque que já tem programado este código. Qq dúvida vamos alinhar melhor em uma conversa.

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdHNlYUp3MVJiZUE

**Comment by matheusgimenez** [comment]
Codigo de produto vai ser o SKU do WooCommerce como já conversamos (só deixando documentado nessa issue)

O resto tá feito!

**Comment by LuwkasLima** [comment]
@diogosp eu vi que o seu comentario esta diferente do Layout e nos desenvolvemos com base no Layout. Desta forma, vou deixar no Label "Pente Fino" pra voce dar uma olhada depois. Nao acho que isso eh tao importante assim pra ser priorizado agora ok?

**Comment by isaquemelo** [comment]
Define melhor essa issue por favor @diogosp =)

**Comment by diogosp** [comment]
@LuwkasLima a questão aqui era a seguinte. mandaram o layout com um botão FINALIZAR COMPRA em todos os produtos e isto caiu em algum momento anterior... por agora to mais não querendo mexer nisso e deixar aprovado.
