### ISSUE TITLE
Página do Produto >> Campo Informações Nutricionais

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#22]
Cada produto terá uma tabela nutricional. Estes campos deverão estar no admin.
Mas deverá ser opcional de aparecer CASO não haja informações digitadas. (isto é: só aparece caso ele tenha info)

<img width="781" alt="screen shot 2016-03-08 at 16 53 39" src="https://cloud.githubusercontent.com/assets/5107285/13614253/5ea2c168-e54e-11e5-9dcd-88c0dfee230b.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdHNlYUp3MVJiZUE

**Comment by matheusgimenez** [comment]
O campo informações nutricionais vai ser simplesmente o editor do WP. O título (informações nutricionais) é uma tag H2 (CABEÇALHO 2) e a linha de separação é um HR ( linha horizontal).

**Comment by LuwkasLima** [comment]
@matheusgimenez se usarmos Shortcodes fica interessante, porque existem shortcodes pra insercao de Tabelas, o que acha?

**Comment by matheusgimenez** [comment]
O que os clientes acharem melhor. Isso é o content do WP, logo, do jeito que quiserem mostrar, deve funcionar!

**Comment by LuwkasLima** [comment]
@matheusgimenez sobre a atualizacao da single de produtos do @isaquebrasileiro pra eu testar esse campo...

**Comment by LuwkasLima** [comment]
Ta OK!
