### ISSUE TITLE
Página do Produto >> Seção Ingredientes

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#23]
Seção de ingredientes - opcional - só aparece em caso de ter informações inseridas.

<img width="715" alt="screen shot 2016-03-08 at 16 56 29" src="https://cloud.githubusercontent.com/assets/5107285/13614429/33cb5198-e54f-11e5-8c02-3c9ca955fbeb.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdHNlYUp3MVJiZUE

**Comment by diogosp** [comment]
É só um campo de texto descritivo.

**Comment by matheusgimenez** [comment]
O campo ingredientes vai ser simplesmente o editor do WP. O título (INGREDIENTES) é uma tag H2 (CABEÇALHO 2) e a linha de separação é um HR ( linha horizontal).

**Comment by diogosp** [comment]
@matheusgimenez pode me explicar melhor como faz isso?

**Comment by LuwkasLima** [comment]
@matheusgimenez explica pra mim tbm q eu faço o teste..

**Comment by matheusgimenez** [comment]
Vai no editar produto nesse produto aqui:

http://dev.brasa.art.br/aboaterra/produto/woo-single-2/

Dentro da página de  edição veja o campo de conteudo padrão do WordPress.

Temos um texto (lorem ipsum), depois do texto uma linha horizontal (HR) e depois da linha horizontal um texto de Cabeçalho 2

**Comment by LuwkasLima** [comment]
Que pergunta idiota caro @luwkaslima...

Aprovadio!
