### ISSUE TITLE
Página Categorias >>  Menu categorias

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#24]
Aqui nós temos como o menu irá operar com o mouse over:
Com imagem destacada junto do dropdown das sub-categorias. Como chamar esta imagem?

<img width="854" alt="screen shot 2016-03-08 at 17 02 08" src="https://cloud.githubusercontent.com/assets/5107285/13614496/957e864e-e54f-11e5-99d1-3451ac5e6d1c.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKTWxVb2ZJakVhSGM

**Comment by matheusgimenez** [comment]
Feito.

Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez voce sabe me dizer porque eu nao consigo achar Categorias de Produtos pra incluir no Menu? Estou entendendo algo errado?

![image](https://cloud.githubusercontent.com/assets/5949986/15231843/1d41ad90-1863-11e6-9f0e-79b9b824e254.png)

**Comment by matheusgimenez** [comment]
Vish, bizarro, era pra ter (e precisa disso pro sistema funcionar)

**Comment by LuwkasLima** [comment]
Burrice nossa, vlw @matheusgimenez!

Segue alguns comentarios:

1 - Acredito que a ideia eh que o Menu seja com "Hover", ou seja, voce passa o mouse e as opções aparecem abaixo:

![image](https://cloud.githubusercontent.com/assets/5949986/15410284/831ac4d2-1dde-11e6-8449-bb8d1c7c85d0.png)

2 - Percebi também que a imagem ao lado é igual ao sub-menu, no exemplo acima, quando você está com o mouse em "Frutas" ele mostra Morangos, se voce esta com o mouse em cima de Legumes, dai a imagem muda pra legumes. É possível fazer isso sem complicar muito as coisas?

Estou colocando isso como parte de uma próxima versão do site, para focarmos na versão BETA primeiro.

**Comment by matheusgimenez** [comment]
1: posso fazer amanhã.

2: é bem chato

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez eu tb quebrei a cabeça pra entender PQ não havia algumas opções pra colocar no MENU. Fucei em alguns fóruns e o lance é BESTA.
É só entrar na página de edição dos MENUS e clicar em OPÇÕES de TELA (botão na direita em cima - ali vc seleciona quais campos quer ver).

**Comment by diogosp** [comment]
@matheusgimenez falta aplicar o HOVER no menu. Isto ficou pra trás.

**Comment by isaquemelo** [comment]
@diogosp tem como explicar melhor essa issue? =)

**Comment by diogosp** [comment]
@isaquemelo o menu das categorias da Loja precisa abrir quando o mouse passa em cima. atualmente o cliente precisa clicar pra abrir as sub-categorias.

**Comment by isaquemelo** [comment]
Feito. No DEV.

**Comment by diogosp** [comment]
@isaquemelo @isaquemelo foi feito sim, mas tem algo errado. o mouse over está acionando pra todos os itens ao mesmo tempo.

**Comment by isaquemelo** [comment]
@diogosp Daqui a pouco posto correção.
