### ISSUE TITLE
Página Categorias >> listagem de produtos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#25]
Listagem simples de produtos das categorias.

<img width="391" alt="screen shot 2016-03-08 at 17 04 32" src="https://cloud.githubusercontent.com/assets/5107285/13614559/e7e638f0-e54f-11e5-9978-dc05a36f6248.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKTWxVb2ZJakVhSGM

**Comment by matheusgimenez** [comment]
Aqui vou precisar de uma ajuda sua @isaquebrasileiro 

Os botões de quantidade (+) (-) estão desalinhados, só preciso deixar como no layout.

**Comment by matheusgimenez** [comment]
Feito.

Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez e @isaquebrasileiro seguem meus comentarios:

![image](https://cloud.githubusercontent.com/assets/5949986/15232173/0a13d606-1865-11e6-84e9-5b2fa3648966.png)

1 - Botao de "Menos" precisa estar ao lado do box de quantidade;
2 - A fonte do preço nao parece a fonte do Layout (podem verificar?). O PSD ta la na pasta do projeto, layout abaixo:

![image](https://cloud.githubusercontent.com/assets/5949986/15232194/2eba0b1a-1865-11e6-801a-00cc40acf4c4.png)

**Comment by LuwkasLima** [comment]
1 - OK
2 - OK

Aprovadiiuu!

**Comment by diogosp** [comment]
Pente fino CSS

- Listagem toda com blocos muito grandes. Diminuir
- Carrinho está enorme
- quadrado da imagem cinza - remover ( só deixar o quadro externo)

**Comment by diogosp** [comment]
Remover o quadro cinza somente da imagem. deixar o externo como no layout

<img width="603" alt="farinhas_ _a_boa_terra" src="https://cloud.githubusercontent.com/assets/5107285/18070800/cb6a172c-6e26-11e6-9326-05ed7e0ccedf.png">
