### ISSUE TITLE
Página de Categorias >> paginação

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#26]
Paginação simples dos produtos de cada categoria

<img width="160" alt="screen shot 2016-03-08 at 17 08 07" src="https://cloud.githubusercontent.com/assets/5107285/13614675/6f077b1e-e550-11e5-910c-caca7ea54557.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKTWxVb2ZJakVhSGM

**Comment by matheusgimenez** [comment]
Feito.

Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez e @isaquebrasileiro so ficou um pelinho:

1 - A seta eh outra, sei que nao eh tao importante assim na perspectiva do desenvolvimento, mas eh muito importante na perspectiva do Designer e principalmente do cliente que espera o mais proximo possivel do Layout que eles aprovaram

![image](https://cloud.githubusercontent.com/assets/5949986/15232230/7b86d824-1865-11e6-87ae-d7e6dd195f44.png)

Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/15232239/86b5f770-1865-11e6-80f6-ac995a643be8.png)

**Comment by matheusgimenez** [comment]
Feito.

Está no DEV

**Comment by LuwkasLima** [comment]
Perfeito!
