### ISSUE TITLE
Página de Cestas >> topo da página

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#27]
Nesta página teremos uma seção abaixo do menu fixo (de categorias) que terá uma imagem destacada e um campo de texto:

<img width="766" alt="screen shot 2016-03-08 at 17 09 32" src="https://cloud.githubusercontent.com/assets/5107285/13614723/a8e44718-e550-11e5-93c2-c41404a01179.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKVmNzVFhUTk9jNFE

**Comment by diogosp** [comment]
@isaquemelo pra fazer esta. São 3 issues da Página de Categorias de Cesta que é personalizada.

**Comment by isaquemelo** [comment]
@diogosp Isso é com o @deshawn @diogosp

**Comment by diogosp** [comment]
@isaquemelo BLZ

**Comment by matheusgimenez** [comment]
Feito. No Dev.
