### ISSUE TITLE
Página de Cestas >> Explicação das Cestas - Bundle Produtcs

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#28]
@matheusgimenez as "cestas" são BUNDLE PRODUCTS. Isto é são KITs de produtos variados de dentro da loja. (cestas de produtos orgânicos: tipo vai cenoura, vai tomate, cebola etc... e cada semana muda).

**Comment by diogosp** [comment]
@matheusgimenez e @LuwkasLima e @isaquebrasileiro 
**O que são as Cestas**
São conjuntos de produtos que já existem individualmente na loja. E que semanalmente o admin do site altera os produtos da cesta de acordo com a disponibilidade

**Quantas cestas existirão?**
Serão apenas 3 cestas. com diferentes tamanhos: cesta mínima, média e completa.

**O que varia nas cestas?**
As cestas não serão somente 1 unidade de cada produto. Por exemplo, a cesta pode ter 3 cenouras, dois pés de alface etc e na próxima semana será diferente.

**E se o cliente quiser mudar?**
O cliente poderá selecionar os produtos avulsos na loja. A ideia da Cesta é facilitar a compra do cliente e dar uma opção de praticamente 1 clique pra comprar uma série de produtos que ele já compra semanalmente.
Portanto, a cesta é só alterável pelo ADMIN.

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima teoricamente o cliente poderá comprar quantas cestas quiser na compra, apesar de ser raro.

**Comment by matheusgimenez** [comment]
@diogosp eu entendo tudo isso, a questão não é essa, to com duvidas se o grouped funciona pra essa funcionalidade ou nao

**Comment by diogosp** [comment]
@matheusgimenez TESTE da Cesta no DEV http://dev.brasa.art.br/aboaterra/produto/cesta-teste-1/

**Comment by diogosp** [comment]
@matheusgimenez https://www.woothemes.com/products/product-bundles/

**Comment by diogosp** [comment]
Solução: utilizar plugin BUNDLE PRODUCTS

https://wordpress.org/plugins/yith-woocommerce-product-bundles/
