### ISSUE TITLE
Página de Cestas >> seção de produtos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#29]
Serão 3 cestas fixas (onde os produtos serão variados por semana, editáveis via ADMIN).
Nesta página das Cestas ela deve puxar as 3 cestas criadas separadamente no WOO. Pra que o cliente compare cada uma delas (e possa clicar em cima e ver quais produtos estão dentro por exemplo)... mas que possa também já inserir no carrinho caso já saiba de tudo.

A single das cestas seguirá a single-product de cestas específico em outra issue criada

<img width="619" alt="screen shot 2016-03-08 at 17 13 35" src="https://cloud.githubusercontent.com/assets/5107285/13614852/30c1197c-e551-11e5-9f81-369aff2315f1.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKVmNzVFhUTk9jNFE

**Comment by diogosp** [comment]
@isaquemelo pra fazer esta. São 3 issues da Página de Categorias de Cesta que é personalizada.

**Comment by matheusgimenez** [comment]
A descriçao em cima possui diferenciaçoes de cores.. alguma ideia de como fazer? Na minha cabeça a unica solução seria um campo de editor, mas não sei, acho que é uma solução completa de mais pra uma string tão pequena.

**Comment by matheusgimenez** [comment]
Feito. No Dev.

**Comment by diogosp** [comment]
@matheusgimenez Dois pente-finos nesta página:

- Em cima está puxando um nome fixo "Cesta Orgânica" nas Cestas. Não consigo tirar isso.
- Abaixo, no resumo é possível quebrar linha ou dar algum espaçamento via HTML? seria ideal criar um parágrafo.

<img width="1119" alt="screen_shot_2016-11-08_at_21_38_31" src="https://cloud.githubusercontent.com/assets/5107285/20122020/e2e02f56-a5fb-11e6-9f55-14a058871e58.png">

**Comment by matheusgimenez** [comment]
> Abaixo, no resumo é possível quebrar linha ou dar algum espaçamento via HTML? seria ideal criar um parágrafo.

Feito. Adicionei possibilidade de quebra de linha.
