### ISSUE TITLE
Home >> Slider de destaques

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#3]
**Carrossel - Banners rotativos - Imagens estáticas **- Logo abaixo do Menu

<img width="1253" alt="captura_de_tela_17_02_16_11_04" src="https://cloud.githubusercontent.com/assets/5107285/13110311/569726d2-d566-11e5-975e-738bd5995a55.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Esse item é um Brasa Slider de nome "Home Slider".

**Comment by diogosp** [comment]
@matheusgimenez as SETAS do Slider estão fora de posição, pra fora da tela da janela.

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
PErfeito! Aprovadiuuu...

**Comment by diogosp** [comment]
@matheusgimenez 
- Setas do Slider estão muito grossas, precisa deixar mais finas
- Não precisa das BOLINHAS marcando qual slide está. Remover.

**Comment by diogosp** [comment]
@isaquemelo daria pra deixar as setas ainda mais finas neste slider principal? e as "bolinhas" pra indicar em qual slide está. Acredito que neste ponto o @matheusgimenez vai precisar te mostrar o  Brasa Slider de uma maneira mais profunda.

**Comment by isaquemelo** [comment]
@diogosp só tirei as bolinhas por que no outro comentário havia uma solicitação para que fosse removido. No próximo commit corrijo isso...

**Comment by diogosp** [comment]
Mas é pra retirar mesmo (mas ela está lá rsrs)


--


*Diogo Soares*
Brasa Design e Tecnologia - www.brasa.art.br <http://brasa.art.br/>
Tel.: (11)  3042-4475

Em 29 de agosto de 2016 20:49, Isaque Melo <notifications@github.com>
escreveu:

**Comment by isaquemelo** [comment]
@diogosp estranho '-' eles aqui não estão aparecendo..

**Comment by diogosp** [comment]
@isaquemelo Pra mim eles aparecem bem encostados na seção abaixo. Quase escondidos

**Comment by isaquemelo** [comment]
@diogosp Amanhã tento jogar pro Dev e vemos o que está acontecendo

**Comment by isaquemelo** [comment]
@diogosp essa ja foi?

**Comment by diogosp** [comment]
Já foi!

**Comment by isaquemelo** [comment]
@diogosp Bereza..
