### ISSUE TITLE
Página de Cestas >> Seção Botões - Bottom

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#30]
Na parte de baixo das cestas ficarão dois textos/botões editáveis para que o cliente saiba que além das cestas ele pode inserir mais outros produtos (portanto o link iria pra página de listagem de categorias)

<img width="586" alt="screen shot 2016-03-08 at 17 17 28" src="https://cloud.githubusercontent.com/assets/5107285/13614973/d5d24d78-e551-11e5-84f8-562e4e7c0db6.png">

Página Completa:
https://drive.google.com/open?id=0B_zOFqExqtsKVmNzVFhUTk9jNFE

**Comment by diogosp** [comment]
@isaquemelo pra fazer esta. São 3 issues da Página de Categorias de Cesta que é personalizada.

**Comment by matheusgimenez** [comment]
Feito. No Dev.
