### ISSUE TITLE
Página do Cliente >> Pedidos já realizados

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#31]
Lista os pedidos já realizados e o status dos atuais.

<img width="757" alt="screen shot 2016-03-08 at 17 23 15" src="https://cloud.githubusercontent.com/assets/5107285/13615121/813f68da-e552-11e5-9145-9667cdc47afa.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKTDNEZWlrVHdsV2M

**Comment by isaquemelo** [comment]
Aguardando @matheusgimenez criar a estrutura base.

**Comment by diogosp** [comment]
Valeu @isaquemelo eu estou entendendo que a base desta página aí é este template aqui. Certo @matheusgimenez ???

http://dev.brasa.art.br/aboaterra/minha-conta/orders/

**Comment by isaquemelo** [comment]
Feito. No DEV.
