### ISSUE TITLE
Página do Cliente >> Detalhes de cada Pedido já feito

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#32]
Aqui mostra mais detalhes dos pedidos já feitos e link para recomprar os mesmos produtos

<img width="645" alt="screen shot 2016-03-08 at 17 25 52" src="https://cloud.githubusercontent.com/assets/5107285/13615178/e2f83ca0-e552-11e5-86db-ae2a01c04aaf.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdkxDOC0yRjFMemc

**Comment by isaquemelo** [comment]
Aguardando @matheusgimenez criar a estrutura base.

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo algumas coisas já estão montadas e previstas no Woo. Outras o Matheus terá que ver como fica mesmo. De repente ele te ajuda nas coisas que já estão prontas pra adiantar.

**Comment by diogosp** [comment]
Aqui estamos trabalhando em cima deste template, certo?

http://dev.brasa.art.br/aboaterra/minha-conta/view-order/178/

**Comment by isaquemelo** [comment]
@diogosp só falta um alinhamento. Nos campos TOTAL, SUBTOTAL e ENTREGA. O resto está feito. (no DEV.)
