### ISSUE TITLE
Página do Cliente >> Dados da Conta

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#33]
Aqui teremos os dados cadastrais do cliente, com as opções de senha e endereço de entrega.

![minha conta 3](https://cloud.githubusercontent.com/assets/5107285/14540833/73197a5c-025d-11e6-8807-fcc48855a008.jpg)

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKYWVlVkpmNi1BMDQ

**Comment by LuwkasLima** [comment]
@matheusgimenez vamos conversar sobre isso, pois precisamos definir o minimo que precisa ser desenvolvido como parte da versao Beta...

**Comment by diogosp** [comment]
@LuwkasLima e @matheusgimenez o que ficou combinado com o cliente disto aqui?
Ficou "pra fazer"?
Me parece que não ficou da maneira como decidimos né?
http://dev.brasa.art.br/aboaterra/minha-conta/

E aqui a página no MODAL não puxou corretamente as configurações do CSS pros títulos

**Comment by matheusgimenez** [comment]
Que página no modal?

**Comment by diogosp** [comment]
@matheusgimenez No modal sim

**Comment by matheusgimenez** [comment]
Só uma coisa, sobre o visual não estar muito igual:

https://woocommerce.wordpress.com/2016/04/21/tabbed-my-account-pages-in-2-6/

O WooCommerce mudou essa página na nova versão e ta bem parecido com o que precisamos.. é só atualizarmos e fazer um pente fino

**Comment by LuwkasLima** [comment]
@diogosp o que decidi foi deixar esta tela no DEFAULT do Woo para a versao BETA. Eles nao precisam de tudo isso que esta no Layout pra operar. Portanto, a pagina abaixo nao foi feita, ela ja vem com o Woo:

![image](https://cloud.githubusercontent.com/assets/5949986/16337328/59f43878-39da-11e6-82c0-2a7c238acd29.png)

Entendam que quando estamos com o projeto atrasado, precisamos dar prioridade ao que eh prioritario. O que deixa eles preocupados quanto as datas de entrega? -> A possibilidade de lancar o site e OPERAR seu Negocio! Simple assim...

Dessa forma, vamos garantir que o site funciona operacionalmente, qualquer pagina outra que nao tenha uma funcao especifica que atrapalha na compra do cliente pode ser colocada em segundo plano e negociada.

**Comment by matheusgimenez** [comment]
DUVIDA 1:
quanto aos multiplos endereços, precisamos pra agora tbm?

Falo isso pq o plugin que eu ia usar não ta muito legal nessa versão do woocommerce, ele leva pra outra página

DUVIDA 2:
e já juntando ai mais uma segunda duvida

os endereços de entrega precisam mesmo ficar na mesma página da minha conta? pq se no futuro eu atualizasse esse plugin e mandasse pra página "Endereços" (uma aba na minha conta) daria pra mandar um PR pra esse plugin

**Comment by diogosp** [comment]
Por isso está pra checar os campos do Woo Matheus.
Precisamos conversar amanhã novamente pra alinhar isso.
A saída seria atualizar o Woo sim.
Não temos.meio termo: ou desde já dizemos que é um erro do layout e
justificamos que não vamos fazer. OU fazemos como está pra agora. Não pode
ser depois.
Amanhã conversamos

Em 24 de ago de 2016 21:14, "Matheus Gimenez Petroni" <
notifications@github.com> escreveu:

**Comment by diogosp** [comment]
@matheusgimenez acordado com o cliente. DEIXAR SOMENTE OS CAMPOS DE ENDEREÇO PADRÃO DO WOO. Isto é, somente 1 endereço de cobrança e 1 de entrega.

**Comment by diogosp** [comment]
@matheusgimenez acordado com o cliente: NÃO HAVERÁ CAMPO DE CRÉDITOS NESTA PÁGINA

**Comment by matheusgimenez** [comment]
O WooCommerce não possui campo de data de nascimento, nem de genero, então nao os terá no site.

**Comment by diogosp** [comment]
@matheusgimenez fui testar a Página Minha Conta que você fez no DEV. mas não consigo "criar" um usuário novo pq ele só retorna a tela de CEP Válido.

http://dev.brasa.art.br/aboaterra/minha-conta/

**Comment by matheusgimenez** [comment]
Minha parte está ok. Falta um pente fino no CSS por parte do @isaquemelo

**Comment by matheusgimenez** [comment]
@diogosp rolou um desentendimento aqui hein, precisamos conversar

**Comment by isaquemelo** [comment]
Minha parte está ok. Aguardando a parte dos pedidos do @matheusgimenez .

**Comment by diogosp** [comment]
@matheusgimenez me aponta aqui o que precisamos ajustar no alinhamento?

**Comment by isaquemelo** [comment]
Feito. No DEV.

**Comment by diogosp** [comment]
@matheusgimenez a Página Minha Conta não está mostrando em Produção. URGENTE

**Comment by matheusgimenez** [comment]
@diogosp Resolvido, era o WC desatualizado
