### ISSUE TITLE
Página de Pagamento >> Completa

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#34]
Aqui vai a página completa de pagamento com as seções agrupadas. Ainda preciso rever este layout. Há botões sobressalentes e ainda precisamos rever se há campos fora do lugar aí (deslocados do fluxo). Quero rever isso com o @matheusgimenez 

<img width="821" alt="psds_final_-_google_drive" src="https://cloud.githubusercontent.com/assets/5107285/14124488/264d68b0-f5dc-11e5-9b02-b22c7fa909bb.png">

Página Completa
https://drive.google.com/open?id=0B_zOFqExqtsKVzlYcEtOVVYzQ1k

**Comment by matheusgimenez** [comment]
Feito: Está no DEV.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro ficou bem legal cara, parabens!....vou colocar meus comentarios em topicos pra ficar mais facil Essa pagina eh bem complicada, pois tem coisa que temos que fazer igual e outras que vamos ter que acionar o cliente pra uma mudanca no Layout. Segue detalhes:

**Dados Pessoais:**

![image](https://cloud.githubusercontent.com/assets/5949986/15232778/22d1d22a-1869-11e6-9971-c4c0d1ed300f.png)

1 - Voce sabe se conseguimos mudar o label de "Primeiro Nome" para "Nome"?
2 - Não precisamos desse campo, ja que as vendas são somente no Brasil (até onde eu sei). Eu não sei bem aonde remover isso, deve ser em configurações do Woocommerce né @matheusgimenez ?

**Entrega:**

![image](https://cloud.githubusercontent.com/assets/5949986/15232826/726273bc-1869-11e6-9ef0-2e731f56f317.png)

3 - Aqui precisa vir de fato o que esta la em cima em **Dados Pessoais**, ou seja, precisamos que a parte do endereco fique separada nessa tela. Essa informacao vai ser utilizada pra calcular o valor dos produtos (que mudam conforme a regiao) e pra calcular o frete. Portanto, conseguimos dividir essas duas partes do formulario em diferentes boxes como no layout?

Obs.: @matheusgimenez como podemos incluir mais campos nesse formulario?

Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/15233016/b66b7b02-186a-11e6-8552-f5be1fb71cd3.png)


![image](https://cloud.githubusercontent.com/assets/5949986/15232912/fdb6701c-1869-11e6-8955-1a6cf648fdf7.png)

4 - Eu vou conversar com o cliente sobre esse ponto, pois me aprece que nao esta dentro do escopo orcado, vamos ter que entender onde vao usar e qual o esforco pra orcar...

**Pagamento**

![image](https://cloud.githubusercontent.com/assets/5949986/15233049/f49fd2ce-186a-11e6-8dea-77808370498b.png)

5 - Conseguimos jogar o campo NOME pra baixo? Assim deixamos mais espaco pro campo do cartao e do Nome no cartao. Veja o Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/15233065/1b6a668a-186b-11e6-8dad-18527cabbe56.png)

**Resumo do Pedido**

![image](https://cloud.githubusercontent.com/assets/5949986/15233094/639ff0dc-186b-11e6-99d2-5e430cfe149d.png)

6 - Eu adicionei 24 produtos no carrinho, e o resumo mostra somente 6 produtos. Precisamos que aparecam todos...

**Comment by isaquebrasileiro** [comment]
"Nome impresso do cartão" - OK, Correção de imagens dos produtos - OK.

**Comment by isaquebrasileiro** [comment]
Em relação aos inputs isso é com o @matheusgimenez

**Comment by matheusgimenez** [comment]
3: você precisa ativar a opção de usar endereço de shipping no woocommerce, ai vai ficar ao lado

4: preciso fazer a parte de mostrar a data/horario de entrega. (aquela mensagem).

**Comment by matheusgimenez** [comment]
Ponto 6: o woocommerce conta a quantidade de produtos no carrinho. Ou seja, contando todos os produtos que vc tem (QUANTIDADE) o valor chega a 24, mas desses 24, vc só tem 6 tipos de produtos. Entende?

**Comment by LuwkasLima** [comment]
Perfeito pessoal!

So ficou faltando o ponto 1 mas eh simplesmente algo que não vai atrapalhar, então vou dar um crédito pra vocês!...hehehe

Muito obrigado! Aprovado..

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima @isaquemelo pessoal, vendo o layout inicial e o resultado final e me parecem BEM diferentes. Sei que pode ter acontecido conversas com o cliente pra adaptar e melhorar. Mas queria bater ponto por ponto:

- Não há HEADER nesta página
- Não há campo de Endereço nos Dados Pessoais, Só no campo de Entrega no meio.
- Não há opções de Taxa de Entrega nesta página, só na anterior antes de fechar o Carrinho.
- O botão do CUPOM está diferente.

![pagina checkout - boa terra](https://cloud.githubusercontent.com/assets/5107285/17144633/c57d3600-532d-11e6-8925-ecdc396f9703.jpg)

**Comment by LuwkasLima** [comment]
@diogosp seguem meus comentarios (por favor, releve a minha falta de memoria, pois faz mais de 2 meses que fiz a apresentacao pra eles e tentei documentar tudo o que pude atraves das Issues pra evitar situacoes como essas)

1 - Header na Pagina: Deixamos o Header da pagina pois nao faria sentido deixar sem Header, ja que a pessoa tem a possibilidade de continuar a navegacao caso queira. Nos vimos que o layout nao tinha header, mas eu pedi pra incluir porque ficaria totalmente fora do contexto, ja que a pagina intermediaria (a do carrinho) tem o header.

2 - Os campos apresentados no site atual sao os requisitados pelo WooCommerce. O Layout nao tomou em consideracao o que o WooCommerce precisa e portanto tivemos que "ignorar o layout". Esse campo de endereco do cliente eh apresentado, mas eh auto-populado se voce estiver LOGADO.

3 - A Taxa de entrega eh simplesmente uma configuracao do WooCommerce para o formato de entrega. Assim que essa configuracao for feita de forma correta, essa tela muda. Novamente, deiamos ela ai porque faz mais sentido do que na outra (a proposito, eu pedi para retirarem do Carrinho).

4 - Sim, ele esta diferente por um problema no box. Tivemos que fazer um workaround para funcionar o cupom e portanto ficar desta forma. Alem disso, dessa forma o botao segue o padrao dos outros boxes.

Como voce comentou no e-mail para eles, eles aprovaram essa pagina quando apresentei, isso precisa ser explicado, pois qualquer mudanca requisitada agora, atrasa as demais partes do trabalho.

Espero ter ajudado.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez 
Tive uma nova conversa com o cliente. E praticamente resolvemos todos os problemas. 
Ficaram dois pontos:

1 - No Layout tem nos DADOS PESSOAIS o **campo CPF**. Ele é necessário pro cliente poder receber a NOTA FISCAL posteriormente (outro sisteminha deles). Precisa aparecer este campo. E vi que comemos bola e não está mesmo na Produção

2 - eu vi que vc comentou no dia 12 de maio o Campo de ENTREGA PORTARIA 24h. E falou que iria conversar com o Cliente. ISTO NÃO ERA UMA FUNCIONALIDADE PRO WOO. Isto era só uma info adicional que vai junto com o pedido do cliente pra avisar o admin da loja quando pode ou não entregar de madruga. @LuwkasLima o que vc combinou com o cliente? era uma coisa simples, um campo de info.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez eu vi a discussão dos campos obrigatórios dos dados pessoais.
o cliente agora mais entrosado com a mecânica do Woo sugeriu uma coisa, vejam se é plausível:

- Já que na parte dos DADOS PESSOAIS era obrigatório colocar o endereço. E no layout há outro espaço para Endereço de Entrega. Não seria o mais adequado que só aparecesse o endereço do cliente e num CHECKBOX ficasse a opção "Quer entregar em outro endereço, clique aqui" E assim ficaria mais simples esta tela.

Sim, isto envolve REPROGRAMAR. mas posso cobrar horas por isso.

**Comment by diogosp** [comment]
FALTA

1 - CAMPO CPF/CNPJ nos dados do cliente

2 - CAMPO ENTREGA PORTARIA 24h. É um campo somente pra informar ao admin da loja que o cliente pode receber na portaria. só informativo.

**Comment by matheusgimenez** [comment]
Tudo feito.

Marco o @isaquemelo agora para fazer uma revisão no front-end.

**Comment by diogosp** [comment]
@matheusgimenez Valeu Matheus! ficou tudo pronto nesta! Obrigado. Só falta CSS mesmo.

**Comment by isaquemelo** [comment]
Feito. No DEV.

**Comment by diogosp** [comment]
Pessoal, Só estou com dúvida no SAIBA MAIS ao lado do campo da Portaria
24h. Ali precisa ter uma mensagem explicativa pra descrever o que significa
o processo de entrega na Portaria. Uma frase já dá


--


*Diogo Soares*
Brasa Design e Tecnologia - www.brasa.art.br <http://brasa.art.br/>
Tel.: (11)  3042-4475

2016-09-07 13:22 GMT-03:00 Isaque Melo <notifications@github.com>:

**Comment by diogosp** [comment]
@isaquemelo preciso de um pente fino aqui. Botão de Endereço Diferente está ficando pra baixo. E não está dando a impressão que é um liga-desliga. Precisa ajeitar isso.

![2016-09-09_13h22_50](https://cloud.githubusercontent.com/assets/5107285/18394474/8be0d60a-7690-11e6-8ff3-68dd29b253d0.png)

**Comment by isaquemelo** [comment]
Ok. Vou colocar estilo padrão.

**Comment by isaquemelo** [comment]
Aplicado.. No Dev. :)

**Comment by diogosp** [comment]
@matheusgimenez sobe pra Produção esta atualização do Isaque, por favor

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo 

- remover título da página "
- remover mensagens de notificação

![selection_004](https://cloud.githubusercontent.com/assets/5107285/18632244/ce7a40fa-7e4c-11e6-8976-4c3237584ace.png)

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo 

Arrumar o CSS da seção da CIELO - o número do cartão está ficando encavalado com a bandeira do cartão

![selection_011](https://cloud.githubusercontent.com/assets/5107285/18632982/88c09b78-7e50-11e6-8dc3-7744bdb8721f.png)

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo 

Quando vão CESTAS pro página de pagamento ele puxa errado a lista de produtos. Deveria puxar como está no CARRINHO.

CARRINHO
![selection_009](https://cloud.githubusercontent.com/assets/5107285/18633031/b8b2cdc4-7e50-11e6-9626-f0e6ae849280.png)

Na Página de pagamento está puxando assim, e quebrando a página (quando é muito produto na cesta). 
![selection_010](https://cloud.githubusercontent.com/assets/5107285/18633052/d224adf4-7e50-11e6-80c3-89ddd8b5225f.png)

**Precisamos de uma lista mais simples como está no Carrinho mesmo.**

**Comment by diogosp** [comment]
@matheusgimenez o que falta aqui:

- quando nesta página entra uma CESTA ele está espaçando muito a lista dos produtos. Pode deixar mais resumido como fica na página do Carrinho. Está aí nos prints acima.

**Comment by matheusgimenez** [comment]
Me explica melhor isso.

**Comment by matheusgimenez** [comment]
Feito! no DEV

**Comment by diogosp** [comment]
@isaquemelo (e @matheusgimenez) 
Isaque precisamos corrigir isto aqui na página de pagamento:

- Está tudo muito pesado, precisa diminuir a fonte (designer)
- A fonte de preenchimento está muito pesada, deixar ROMANA (NORMAL), está bold.
- remover campo NOME DA EMPRESA no cadastro (deixar o CNPJ)
- Deixar a fonte dos campos de preenchimento ROMANA tbem. 
- Botão APLICAR CUPOM deixar mais DISCRETO - remover o botão e deixar somente o link (no layout está claro isso)
- diminuir fonte da área do pagamento cartão (deixar igual o restante dos campos preenchíveis)
- retirar o menu da loja nesta página também PAGAMENTO

- Resumo do pedido ainda está quebrando a linha do produto na lista de resumo
<img width="1392" alt="finalizar_compra_ _a_boa_terra" src="https://cloud.githubusercontent.com/assets/5107285/19537535/1e7336f8-962f-11e6-88f7-e3410531434a.png">

**Comment by isaquemelo** [comment]
1 - Fontes foram reduzidas em 20%.
2 - Todas as fontes exceto as que requerem fonte em BOLD foram colocadas em text-style normal.
3 - @matheusgimenez 
4 - Feito.
5 - @matheusgimenez 
6 - Todos os campos foram padronizados.
7 - @matheusgimenez 
8 - @matheusgimenez não sei bem o que podemos fazer aqui mano.

**Comment by diogosp** [comment]
@matheusgimenez recebi mais um problema.
- o uso de cupom na página de pagamento não está funcionando. Somente no carrinho está correto.

**Comment by diogosp** [comment]
@matheusgimenez atualizando decisão do cliente: REMOVER campos de CUPONS da página de pagamento.
Deixar somente no CARRINHO (como já está.

**Comment by matheusgimenez** [comment]
Nome da empresa: Feito;
Remover menu: feito;
Remover aplicar cupom: feito;

**Comment by diogosp** [comment]
@matheusgimenez os produtos no resumo do pedido ainda estão quebrando a linha (nome e quantidade estão muito espaçados). É a última pendência aqui.

**Comment by matheusgimenez** [comment]
Como deveria ficar isso? Alguma sugestão?

**Comment by diogosp** [comment]
@matheusgimenez ainda está quebrando um pouco a linha. Tipo o ideal é que ele ficasse tudo numa mesma linha mesmo, com texto corrido.

<img width="400" alt="screen_shot_2016-12-18_at_12_05_12" src="https://cloud.githubusercontent.com/assets/5107285/21294001/5516a2ca-c51a-11e6-8842-b6b03a64c315.png">

**Comment by matheusgimenez** [comment]
@diogosp Vc verificou onde? em local e dev ta ok!

Segue screenshot no dev:

![screenshot from 2017-02-15 17 04 53](https://cloud.githubusercontent.com/assets/4724804/22990622/f44b6c2c-f3a0-11e6-8330-1671cde764a7.png)

**Comment by diogosp** [comment]
@LuwkasLima vc chegou a validar alguma destas pendências com o Julio?

**Comment by LuwkasLima** [comment]
@diogosp não conversei com eles sobre nenhuma das pendências. A unica coisa que foi conversada com eles foi o contrato (apresentação) e as demandas novas que fazem parte do novo orçamento. Não fizemos mais nenhuma conversa e eles também não nos cobraram (pelomenos eu não recebi nenhuma cobrança por e-mail direta).
