### ISSUE TITLE
Single das Cestas >> Completa

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#36]
A single das cestas (bundle) será diferente da single-product normal apenas com a listagem dos produtos inseridos no kit ao lado da imagem. No meio da página.

<img width="454" alt="screen shot 2016-03-08 at 17 36 44" src="https://cloud.githubusercontent.com/assets/5107285/13615512/6d8534ee-e554-11e5-9cc3-0677aa72203e.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKMVV0bmZDWXZ4TzA

**Comment by LuwkasLima** [comment]
@matheusgimenez entendo que esta pagina ja esta praticamente pronta, so precisamos fazer os ajustes de CSS da Single que acredito que o @isaquebrasileiro ja fez..

**Comment by isaquebrasileiro** [comment]
@LuwkasLima essa já tá ok :)

**Comment by LuwkasLima** [comment]
@isaquebrasileiro ficou show!

So tem uma coisinha cara, eu percebi que existe um alinhamento entre os itens da pagina do produto e o menu de categorias acima que da um pouco mais de espaco entre os elementos. Nao sei se voce fez com que a parte debaixo fosse mais "fina" de proposito ou se foi sem querer, da uma olhada:

![image](https://cloud.githubusercontent.com/assets/5949986/15371052/50284958-1cff-11e6-9035-16bd0a4593f6.png)

**Comment by LuwkasLima** [comment]
@isaquebrasileiro conseguiu ver esse aqui?

**Comment by isaquebrasileiro** [comment]
@LuwkasLima já está quase pronto.

**Comment by isaquebrasileiro** [comment]
@LuwkasLima feito.

**Comment by LuwkasLima** [comment]
@matheusgimenez sobe ai quando der pra eu checar..

**Comment by LuwkasLima** [comment]
@isaquebrasileiro vc so fez pra Cestas ou ele se ajusta a partir do conteudo de cima?

![image](https://cloud.githubusercontent.com/assets/5949986/15411730/84e5a454-1de7-11e6-9978-725141a677f9.png)

**Comment by isaquebrasileiro** [comment]
Apenas para as cestas @LuwkasLima

**Comment by LuwkasLima** [comment]
@isaquebrasileiro eu ate entendo o porque voce decidiu fazer somente com as Cestas (e acho que prefiro assim). No entanto, vendo os Layouts (que foram aprovados pelo cliente) eu percebo que se aplica a qualquer Produto. Desta forma, vou pedir pra que voce aplique as mesmas modificacoes nas paginas de produtos simples, tudo bem?

Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/15429538/ffe5ce16-1e66-11e6-83d5-06d2170d7f4a.png)

**Comment by diogosp** [comment]
@isaquemelo 
Acredito que com algumas mudanças no tamanho da estrutura e eles colocando conteúdo a Single das Cestas desconfigurou toda. 
Mando o print de duas cestas que estão com problema e seus links

https://aboaterra.com.br/produto/cesta-pequena-organica-a-boa-terra/
https://aboaterra.com.br/produto/cesta-grande-organica-a-boa-terra/

![selection_003](https://cloud.githubusercontent.com/assets/5107285/18631988/75cb24ac-7e4b-11e6-820b-7a1444fe5739.png)
![selection_002](https://cloud.githubusercontent.com/assets/5107285/18631992/7850c470-7e4b-11e6-82e3-fc1487c9e716.png)
