### ISSUE TITLE
Página do Produto >> Rodapé Livro

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#37]
Haverá abaixo da seção ingredientes (outra issue) em TODOS os produtos a chamada para a venda de um livro de receitas. É para a single product e pra single das cestas também

<img width="789" alt="screen shot 2016-03-08 at 17 40 46" src="https://cloud.githubusercontent.com/assets/5107285/13615617/10e37344-e555-11e5-85db-677030adb19f.png">

Ao clicar em COMPRAR cai na Single do Livro.

AO CLICAR no SAIBA MAIS abre-se um lightbox com explicações:

<img width="871" alt="screen shot 2016-03-08 at 17 44 15" src="https://cloud.githubusercontent.com/assets/5107285/13615682/697952bc-e555-11e5-91bc-3b1140389ed3.png">

Página completa:
https://drive.google.com/open?id=0B_zOFqExqtsKdHNlYUp3MVJiZUE

**Comment by matheusgimenez** [comment]
Feito
