### ISSUE TITLE
HOME >> Seção Fresquinhos da Nossa Horta

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#38]
Seção abaixo da área da Newsletter. Seção para puxar Destaques de produtos que o cliente quer colocar na Home e trocar periodicamente

<img width="1019" alt="screen shot 2016-04-11 at 17 39 51" src="https://cloud.githubusercontent.com/assets/5107285/14441700/6b6ee8c6-000c-11e6-9ae9-f4b7c0c7142e.png">

**Comment by matheusgimenez** [comment]
Essa area resolvi com widget (achei que faz mais sentido que usar a api do customizer.. assim consigo reusar em outras areas).

O widget se chama "WC Query por tags", para usar é só adicionar ele na area de widgets desejada e colocar no campo de tag o slug da tag desejada.

**Comment by diogosp** [comment]
@matheusgimenez mesma dúvida aqui: eu coloco quantas TAGs eu quiser? é só separar por vírgulas?

**Comment by LuwkasLima** [comment]
@diogosp so eh possivel colocar 1 tag. Portanto, para que eles possam escolher os produtos que aparecem nessa area, eu proponho que uma Tag chamada "**Fresquinhos**" seja criada e eles a colocam nos produtos que desejam que apareca nessa secao.

Exemplo:

![image](https://cloud.githubusercontent.com/assets/5949986/15194190/482f607e-1787-11e6-8a2e-426dc41166b4.png)


Link: http://dev.brasa.art.br/aboaterra/produto-etiqueta/fresquinhos/
