### ISSUE TITLE
FRONT-END: Página de produto ( SINGLE )

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/aboaterra-theme#39]
![pagina_produto_2](https://cloud.githubusercontent.com/assets/4724804/14784081/2fee3f4a-0aca-11e6-9c3b-1023f1f538ff.jpg)

Nesse issue precisamos deixar as funções do WooCommerce com a cara do layout. A parte de cima, onde exibe o produto, vc não vai mexer, isso vai ficar pra mim.

Preciso que vc estilize os comentarios (reviews) sendo que esses não foram propostos no layout.

**Comment by diogosp** [comment]
@matheusgimenez vc já definiu aí como será este campo de Informações Nutricionais? Pq acho que seria interessante ser um campo de txt/html aberto onde eles pudessem descrever amplamente (e inserir tabela caso fosse necessário). Ou vc já fechou que serão campos fixos no produto? seria bom ser o campo de DESCRIÇÃO DO PRODUTO. Pra ficar bem claro que eles podem mexer no futuro e inserir diferentes tipos.

**Comment by matheusgimenez** [comment]
Pensei nisso mesmo, em ser o campo de edição do post.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro e @matheusgimenez seguem os apontamentos do que precisa ser feito:

![image](https://cloud.githubusercontent.com/assets/5949986/15196012/03f7d432-1790-11e6-9e71-cc04216c3895.png)


1 - Botões Menores com a Fonte do Layout
2 - Remover Categorias e Etiquetas
3 - Remover Texto Lateral (essa descrição so vai la em baixo, em INGREDIENTES)

Como esta no Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/15196026/16b440d8-1790-11e6-99d6-85969f7755fe.png)

**Pergunta:** Como fica a area "INGREDIENTES"?

**Comment by LuwkasLima** [comment]
@isaquebrasileiro pede pro @matheusgimenez subir no dev e me avisa pra eu testar, parece que nao ta la ainda..

**Comment by LuwkasLima** [comment]
@isaquebrasileiro segue acredito que ultimos comentarios:

1 - Desculpe, eu nao percebi que havia um pequeno texto abaixo do botao de comprar onde diz "Receba na porta da sua casa com uma taxa unica de R$9,00"

![image](https://cloud.githubusercontent.com/assets/5949986/15370547/232ce424-1cfd-11e6-8a7c-f483b6b615ec.png)

Eu nao sei se isso tem a ver com algo que o @matheusgimenez ia fazer (algo que calculasse a taxa de entrega com base na regiao talvez?). Em fim, vou tentar alinhar isso com o cliente, preciso entender melhor o que ele quer ai..

2 - A fonte que estao utilizando para os botoes eh a que eles nos enviaram nos PSDs? Porque aqui no Chrome ela nao aparece igual ao que esta no Layout, veja:

Layout:
![image](https://cloud.githubusercontent.com/assets/5949986/15370665/92521b9e-1cfd-11e6-9723-e2d934acb79b.png)

Chrome + Windows:
![image](https://cloud.githubusercontent.com/assets/5949986/15370684/a23df6f4-1cfd-11e6-8c52-a97be52a9813.png)

3 - @isaquebrasileiro consegue mudar o nome do botao "COMPRAR" para "ADICIONAR NO CARRINHO" igual ao Layout?

![image](https://cloud.githubusercontent.com/assets/5949986/15370931/c3feccd6-1cfe-11e6-8495-351aa79cca88.png)

**Comment by matheusgimenez** [comment]
É a mesma fonte, @LuwkasLima.

**Comment by isaquebrasileiro** [comment]
Tópicos 3 e 2 fechados.

**Comment by LuwkasLima** [comment]
@matheusgimenez acho que vc nao subiu no DEV o Branch do Isaque ainda, certo?

![image](https://cloud.githubusercontent.com/assets/5949986/15409640/4a74895e-1ddb-11e6-9765-62b2009a4692.png)

**Comment by LuwkasLima** [comment]
@isaquebrasileiro preciso conversar com o cliente para entender essa frase do Layou. Vou deixar isso no gelo por enquanto para focarmos no que importa.
