### ISSUE TITLE
Home >> 3 botões de Destaques

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#4]
3 botões personalizáveis clicáveis com efeito de mouse over. Abaixo do banner.

<img width="930" alt="home_4_jpg" src="https://cloud.githubusercontent.com/assets/5107285/13110490/87f66566-d567-11e5-9458-94f357bcd4a7.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Esse item ficou como um Brasa Slider. Precisa criar/editar o item Slider Destaques.

**Comment by diogosp** [comment]
Diminuir os quadros de acordo com o layout. Estão muito grandes. Há espaços aos lados que deveriam estar em branco
