### ISSUE TITLE
Página Carrinho de compras (CART)

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/aboaterra-theme#40]
LAYOUT:

https://drive.google.com/open?id=0B_zOFqExqtsKODd5TVkzM0NxWjg

**Comment by matheusgimenez** [comment]
Feito

Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou certinho cara, so vou fazer comentarios bem pequenos, mas deixa isso por ultimo OK? Vamos focar em deixar a versao BETA funcional e depois voltamos aqui...

![image](https://cloud.githubusercontent.com/assets/5949986/15297530/430a1620-1b60-11e6-9934-8371a194fa42.png)


1 - Fonte do box de Cupom de Desconto precisa ser a mesma do Nome do Produto e etc...
2 - Nao sera "Finalizar Compra" mas sim "Fechar Pedido"

**Comment by diogosp** [comment]
Pente fino CSS

- os botões finalizar compra e continuar comprando são do mesmo tamanho, e o contunuar comprando está fora de centro. As fontes são do mesmo tamanho, no site estão de tamanhos diferentes.

**Comment by diogosp** [comment]
Pente Fino:
- quando o cliente clica no CARRINHO no HEADER - o LARANJA que aparece é diferente do restante do site.

![2016-09-09_12h43_49](https://cloud.githubusercontent.com/assets/5107285/18393270/188f0442-768b-11e6-85a5-636074511cdd.png)

**Comment by diogosp** [comment]
@matheusgimenez  sobe pra Produção isto tb.

**Comment by diogosp** [comment]
@matheusgimenez Matheus, quando insiro qq coisa no carrinho depois de passar pelo Modal ele não está dando refresh na página e não adiciona na contagem do carrinho no Header. o cliente está sem saber (sem dar refresh manualmente ou mudar de página) se o produto entrou ou não no carrinho.

**Comment by diogosp** [comment]
@isaquemelo o texto do Botão "Finalizar Compra" está errado. o correto é "FECHAR PEDIDO". Por favor corrigir. 
https://aboaterra.com.br/carrinho/

![selection_008](https://cloud.githubusercontent.com/assets/5107285/18632649/e198d596-7e4e-11e6-8a5c-19a223c0c6a4.png)

**Comment by diogosp** [comment]
@matheusgimenez precisamos inserir o BOTÃO **"ATUALIZAR CARRNHO"**. Pegando por este layout eles pediram pra colocar Acima do botão CONTINUAR COMPRANDO. Só segue este layout padrão, coloca em laranja,

**Comment by matheusgimenez** [comment]
@diogosp feito!

Corrigi também o nome do botão "Fechar Pedido"

**Comment by diogosp** [comment]
Matheus, ficou perfeito. Pode mandar pra produção


--


*Diogo Soares*
Brasa Design e Tecnologia - www.brasa.art.br <http://brasa.art.br/>
Tel.: (11)  3042-4475

2016-09-19 20:43 GMT-03:00 Matheus Gimenez Petroni <notifications@github.com
