### ISSUE TITLE
Calculo de Preço com Base na Região

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/aboaterra-theme#41]
O site precisa utilizar uma lógica que é crucial para o funcionamento do fluxo de compra, um mecanismo que calcula o preço dos produtos com base na região do cliente (a região é a cidade do cliente, informação que vem do seu perfil de cadastro e é apresentada aqui na página abaixo)

![image](https://cloud.githubusercontent.com/assets/5949986/15233359/b051b3dc-186d-11e6-8e52-0fb7fad46097.png)

Como funciona?

O cliente se cadastra e define um endereço de entrega que por sua vez possui uma Cidade:

![image](https://cloud.githubusercontent.com/assets/5949986/15233409/1c298ff8-186e-11e6-90a8-54283ee80285.png)

Com essa informação, quando o cliente loga no sistema para fazer sua compra, os preços dos produtos são atualizados para o preço praticado na Cidade dele.

Obs.: Essa funcionalidade é bem complicada, vamos conversar com calma pra buscar a melhor opção...

**Comment by LuwkasLima** [comment]
Depois da conversa com o @matheusgimenez ficou acordado que vou fazer testes pra verificar se a funcionalidade de precos com base no CEP esta funcionando como esperado...

**Comment by LuwkasLima** [comment]
@matheusgimenez encontrei 3 probleminhas, seguem detalhes:

**1 - Preço por região não está funcionando para Cestas (Produtos Bunddle):**

@matheusgimenez assim como explicado por Chat, esse problema só acontece com CESTAS, quando marco "Set Price Manually" o preço para a região cadastrada e clico em Atualizar o produto, a seleção volta para o anterior sem salvar o preço.

**Antes de salvar:**

![image](https://cloud.githubusercontent.com/assets/5949986/15338096/fce679b0-1c43-11e6-8c56-de75b4b5a972.png)

**Depois de salvar:**

![image](https://cloud.githubusercontent.com/assets/5949986/15337986/a5e78866-1c43-11e6-906c-8562a7797dfc.png)

Teste feito com este produto (Cesta): http://dev.brasa.art.br/aboaterra/produto/cesta-2/

**2 - Modifiquei a quantidade de produtos no Carrinho (ao inves de 2 coloquei 1) e o preço nao atualizou, nem na pagina do carrinho, nem na pagina seguinte (finalizar compra). - Acredito que precisamos de um botao pra "Atualizar Total":**

![image](https://cloud.githubusercontent.com/assets/5949986/15338782/07935312-1c47-11e6-8ccf-637aaeb65489.png)

Proxima pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/15338815/278625e6-1c47-11e6-9e66-5334dc19e243.png)


3 - Eu fiz um teste esperto pra ver como o sistema reagia. Eu sou um comprador de Bragança (meu CEP de cobrança é BRAGANÇA) mas estou comprando para entrega em SÃO PAULO (CEP de SP no endereço de entrega).

Percebi que nesse esquema, o site todo fica com o valor do meu endereço de cobrança, mas somente se marco "Entregar para um endereço diferente" é que ele atualiza o valor do Pedido no lado direito (no entanto, fica uma inconsistência com relação ao preço do produto e o total, veja abaixo)


![image](https://cloud.githubusercontent.com/assets/5949986/15338941/b417c4ba-1c47-11e6-981e-8d5d89fbe277.png)

**Comment by matheusgimenez** [comment]
1 - Resolvido 

3 - Resolvido a diferença no valor total. Quanto a diferença de preços no site inteiro, pense que faz sentido sim. O endereço de entrega é o endereço de entrega, ou seja, na hora da entrega o cara vai selecionar ele e além disso teremos mais de um preço de entrega, a ser escolhido na hora de finalizar.

**Comment by LuwkasLima** [comment]
1 - Esta OK!

2 - Definimos que vou alinhar com o cliente esta necessidade, ja que nao faz parte do Layout

3 - O Sub-total e Total estao atualizando corretamente, no entanto, ainda ficamos com a inconsistencia dos produtos aparecerem com o valor do Endereco de Cobranca. 

![image](https://cloud.githubusercontent.com/assets/5949986/15369494/72f1461c-1cf8-11e6-8145-81c52cc1e3bf.png)

Eu so vejo 2 saidas possiveis:

1 - Atualizamos esse valor de cada produto nessa area de RESUMO DO PEDIDO, ou...

2 - Definimos que o valor dos produtos no site PRECISAM ser alinhados ao Endereco de Entrega (so que nesse caso, quando implementarmos 2 ou mais enderecos de entrega por cliente, vamos ter que colocar algo para o cliente marcar qual eh o "Default" e assim calculamos com base nele).

Qual solucao parece melhor pra voce @matheusgimenez ?

**Comment by LuwkasLima** [comment]
Atualizando...

1 - Esta OK!

2 - Definimos que vou alinhar com o cliente esta necessidade, ja que nao faz parte do Layout

3 - @matheusgimenez definiu que faremos a atualizacao dos precos de cada produto na tela de finalizacao de compra, com base na mudanca de CEP

4 - Foi resolvido, configurando-se forma de entrega no Woo

**Comment by matheusgimenez** [comment]
Ponto 3 está resolvido!

**Comment by LuwkasLima** [comment]
Aprovado pra versao BETA @matheusgimenez !

**Comment by LuwkasLima** [comment]
@matheusgimenez como mencionado, o botao para aplicar o Cupom de Desnconto nao esta funcionando:

![image](https://cloud.githubusercontent.com/assets/5949986/15403402/69ee1952-1dbe-11e6-9c8e-a988adaf8750.png)

**Comment by matheusgimenez** [comment]
Feito!

**Comment by LuwkasLima** [comment]
@matheusgimenez só tem um problema, o valor do desconto não ta aparecendo na página. Eu sei que não temos no Layout, mas isso é com toda a certeza item obrigatório pra transparência do processo de compra. Minha sugestão é aplicar o desconto com o estilo do "sub-total".

![image](https://cloud.githubusercontent.com/assets/5949986/15433924/1c9a6a72-1e7a-11e6-836d-7d3ac6a37c12.png)

**Comment by matheusgimenez** [comment]
Esperava isso.. mas devo fazer isso agora ou é uma issue de pente fino?

**Comment by LuwkasLima** [comment]
@matheusgimenez como comentado no chat, pode deixar espirrar pra semana que vem, mas precisamos disso antes de eles lancarem no dominio final, entao provavelmente nao pode passar da semana que vem, ou seja, fica como prioridade acima do restante que vier...

Obrigado mais uma vez pelo otimo trabalho...

**Comment by matheusgimenez** [comment]
Resolvi esse.

**Comment by LuwkasLima** [comment]
Perfeito hermano!

**Comment by LuwkasLima** [comment]
@matheusgimenez conversei com a cliente e vamos esperar eles enviarem detalhes sobre onde posicionar o botao de "Atualizar Carrinho". Infelizmente isso vai gerar problemas pros clientes se for lancado sem isso...

Estou esperando eles voltarem com a info, oK? Vou deixar comigo aqui..
