### ISSUE TITLE
[Prioridade 2] Verificação de CEP atendido pelo Sítio

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/aboaterra-theme#42]
Precisamos desenvolver um mecanismo de verificação de CEP para que os clientes, quando entrarem no site do Sítio, possam verificar se o Sítio entrega em sua residência. Como isso é feito?

Em algumas páginas do site, existe um campo de validação de CEP como este:

![image](https://cloud.githubusercontent.com/assets/5949986/15615448/06674ee8-2404-11e6-9dac-0e6764a1c030.png)

Uma das Páginas que possui esse campo: https://drive.google.com/drive/folders/0B8Nss0g77Q6cbW56TG9rX2FMYzA

O cliente entra com o CEP e o sistema verifica na lista de CEPs cadastrados por Região, se o CEP está nessa lista (ou seja, vai buscar nos CEPs cadastrados no Painel de Controle do WordPress:

![image](https://cloud.githubusercontent.com/assets/5949986/15615466/40a4b898-2404-11e6-95db-4d23ea40ce5f.png)

Caso o resultado seja NEGATIVO o cliente é redirecionado a uma outra página:

![image](https://cloud.githubusercontent.com/assets/5949986/15615541/979b9126-2404-11e6-9f1a-499fff7ef829.png)

1 - Mensagem customizável da página;
2 - Botão que volta a página que ele veio para que possa colocar outro CEP;
3 - Botão que leva ele para a Home;
4 - Lista de Regiões cadastradas no sistema;
5 - Essa funcionalidade não será possivel até onde eu entendi. Pois cadastramos Regiões como Cidade e não como Bairro. Não sei bem como resolver isso...

**Comment by matheusgimenez** [comment]
Feito. A página no caso de não existir eu fiz com modal.

Precisa colocar nas configurações (CUSTOMIZER -> MENSAGENS/INFOS DE ENTREGA) a mensagem com o link para o modal.

Exemplo de mensagem: 
`Infelizmente não atendemos essa CEP. <a href="http://localhost/aboaterra/regioes-atendidas-modal/">Veja as regiões atendidas</a>`

**Comment by matheusgimenez** [comment]
OBS: A mensagem quando for possivel entregar é configurada no plugin de Regiões.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez fui olhar a ferramenta novamente. Vocês chegaram a ver como funciona o lance de CEPs no BR? Pq o ideal teria sido implementar RANGES de CEPS. Pq há uma norma que organiza pequenas variações de numeração de acordo com o lado da rua, par-impar etc.

Pra ficar num exemplo: o CEP da minha RUA é 01226-000. Contudo, os CEPs 01226-001 e 002 existem são utilizados também principalmente pra controle interno dos Correios.

Sim, poderíamos excluir o final dos CEPs pra facilitar. Mas aconteceu que em cidades pequenas há CEPs que cobrem regiões inteiras e não ruas. Então acho que daria pau.

É possível via PHP ou JS fazer ele entender que uma **FAIXA de CEPs** é abrangido se colocarmos um numero menor e maior? A questão é que pra SP teríamos na **MESMA REGIAO** diversas faixas:

**Água Branca 4   do 05001-000 até 05043-070**

**Comment by matheusgimenez** [comment]
@diogosp nao entendi

**Comment by LuwkasLima** [comment]
@diogosp Tipo, nao entendi o problema da questao, se eh o cadastro de CEPs no plugin de preco ou a BUSCA de CEPs na pagina de busca pelo CEP, sacou?

**Comment by diogosp** [comment]
@LuwkasLima e @matheusgimenez.
É no CADASTRO DE CEPS na Região.
o Admin do site deveria ter a opção de cadastrar ao invés de número por número, colocar um RANGE. Pode não parecer lógico, mas CEPs são SEQUENCIAIS, uma região engloba sequencias que vão de (exemplo) de 100 a 199. Pra que vou cadastrar 100, 101, 102, 103, 104...... se posso falar pro sistema: 100 ao 199 é tal região?

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez só tem UMA particularidade. Cada região precisa poder cadastrar alguns RANGES diferentes. Não pode ser um range por região. Pq? Pq SP existe e cada bairro é um range e eles querem manter como uma região só.

**Comment by diogosp** [comment]
@matheusgimenez só pra registrar a conversa. Sobre os Ranges de CEPs ele funciona colocando * (asterisco) em alguma posição do CEP completo (sem hifen) e assim ele puxa os números completos de 0 a 9.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez 

- [ ] Busca por CEP - retorno positivo e negativo

- [ ] Ajax com a resposta NEGATIVA é possível colocar um link para a página de regiões de entrega. @LuwkasLima vc viu esta solução do Matheus? Ele chama o botão com um LINK pra página das regioes, não vai automaticamente pra página. O que vc acha? Suficiente?

<img width="390" alt="screen shot 2016-06-23 at 14 45 45" src="https://cloud.githubusercontent.com/assets/5107285/16313788/30786610-3951-11e6-9827-ff46c6fa8530.png">

- [ ] Editor de Mensagens de CEP positivas - Dentro da Região pra poder configurar mensagem com dias de entrega

- [ ] Mensagem de CEP negativo - Editor no Customizer pra alterar.

**Comment by LuwkasLima** [comment]
@diogosp isso pra mim esta perfeito. So que esse LINK, na minha opiniao, precisa ir pra uma pagina que retorne para a pagina de Login/cadastro. Ainda nao tem um caminh de volta depois que vc clica no link.

**Comment by diogosp** [comment]
@LuwkasLima confesso que me perdi no seu comentário. Você viu lá que no Customizer dá pra editar a URL, ela vai pra onde o Admin do site quiser. Já existe esta página que você está falando? Precisamos criar? O que efetivamente precisa mudar?

**Comment by LuwkasLima** [comment]
@diogosp Eh so tomar o cuidado de colocar um botao ou link pra pessoa voltar pra pagina onde ela digitouno CEP. Se nao ela eh jogada pra pagina de regioes, le as regioes e nao sabe o que fazer depois (tem que fechar o modal, clicar no carrinho pra abrir DE NOVO a pagina de login/cadastro

**Comment by diogosp** [comment]
@LuwkasLima cara, eu não estou conseguindo visualizar a sua proposta. desculpe mesmo, eu que to confuso aqui com a mecânica proposta.

Tentando arquitetar passo a passo:
- usuário digita CEP que não existe pra entrega
- Abre o ajax com a mensagem e o link pro modal das regiões
- Pessoa se cadastra ou faz login
- pessoa volta pra Home com alguma mensagem de preços atualizados pra região dela

É isso? O que estou tentando entender é se é preciso só direcionar a URL correta ou se é preciso desenvolver um fluxo melhor pra fechar o caminho pro usuário. Mas não consigo visualizar tudo.

Eu acho que vamos precisar de 20 min. de conversa com o Matheus e nós pra vermos o melhor caminho. Tem algo falhando aí no fluxo.

**Comment by diogosp** [comment]
Resultado da reunião 24/06. @LuwkasLima @matheusgimenez 
no Modal de verificação do CEP:

- [ ] Se eu entro com meu cadastro já feito. Ele insere o produto no carrinho e retorna o usuário pra página de origem. Atualizando automaticamente a barra superior com o CEP cadastrado.

- [ ] Se o usuário optar por cadastrar um novo usuário, pedir obrigatoriamente o preenchimento do CEP no MODAL, além de E-mail e Senha. Volta pra Home com a barra superior atualizada com o CEP preenchido.

- [ ] Colocar o ajax com a mensagem do dia de entrega no checkout junto com o RESUMO DO PEDIDO abaixo do frete. 

- [ ] No checkout re-confirmar o CEP de entrega e aparecer os ajax verde e vermelho caso não seja atendido.

**Comment by diogosp** [comment]
@matheusgimenez e @LuwkasLima 
decisões com o cliente:

- [ ] Em relação à página de cadastro está ok deixar o CEP junto com Nome, E-mail e Senha. E podemos tirar a frase “ Quero informar meu CEP antes para verificar se entregam na minha casa”.
Portanto, podemos deixar simples mesmo com a verificação do CEP e com a possibilidade de cadastro do email e senha

- [ ] Retirar o Ajax de resultado NEGATIVO do CEP. Ele quer que caia DIRETO na Página de Regiões de Entrega e o texto pra explicar pro usuário testar outro CEP.

- [ ] Só aparecer o AJAX em caso de CEP POSITIVO. Com a mensagem personalizada cadastrada na região. E voltando pra URL onde o cliente estava, mostrando na barra superior o CEP digitado.

- [ ] Colocar o ajax com a mensagem do dia de entrega no checkout junto com o RESUMO DO PEDIDO abaixo do frete.

- [ ] No checkout re-confirmar o CEP de entrega e aparecer os ajax verde e vermelho caso não seja atendido.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez 
FAIXA DE CEPS
Bom pessoal, precisamos nos alinhar aqui numa reunião básica pra tentar definir um caminho pra solução backend pro preenchimento de CEPs.

O ideal é que ficasse como montei na imagem:
Criação de sub-regiões. cada sub-região com nome e com dois campos de Início e fim da faixa de CEPS.

Se vocês acham adequado manter a fórmula no campo OK. Se desse pra simplificar SEM INTERFACE, tipo se desse pra montar no campo ali um exemplo 5001*5430. Que puxaria do numero 5001 ao 5430 (e nos caso o asterisco seria o ATÉ). Existe isto como possibilidade?

**Comment by matheusgimenez** [comment]
Gostei da ideia do sem interface
Poderia ser:
12910610|1910620?
O que acha?

**Comment by diogosp** [comment]
@matheusgimenez EXCELENTE.

**Comment by diogosp** [comment]
@matheusgimenez Matheus, existe a possibilidade de colocarmos os nomes das sub-regiões dentro deste campo dos CEPs? Teria como escrever algo lá sem prejudicar o sisteminha pra buscar os CEPs?
Tipo - "Bom Retiro - 12910610|1910620"

**Comment by matheusgimenez** [comment]
Fazemos assim então:

Será um CEP por linha com o nome antes com um "-" separando. ok?

**Comment by diogosp** [comment]
@matheusgimenez MELHOR AINDA

**Comment by matheusgimenez** [comment]
Feito o sistema de cadastro de CEPs.

**Comment by diogosp** [comment]
@matheusgimenez ótimo Matheus, vou testar amanhã

**Comment by diogosp** [comment]
@diogosp @deshawn vc poderia me explicar como funciona o lance do cadastro de CEPs novo? Precisamos documentar isso e não entendi direito lá na interface pq está tudo a mesma coisa

**Comment by matheusgimenez** [comment]
@diogosp no campo de CEPs vc coloca por exemplo:
Bragança Paulista - 12910610|12910640

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima só pra documentar:
Alterações pra inserção da faixa de CEPS está OK. 

Formato é
NOME DA SUB-REGIAO - HIFEN COMO SEPARADOR - CEP INICIAL e CEP FINAL DA FAIXA separados por "|"

EXEMPLO:
Bragança Paulista - 12910610|12910640

*Obs.: os CEPS não podem estar com o o hifen, não está funcionando. Precisa ser o número corrido.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez 

Galera, não dá pra usar a DEFAULT REGION como base pro site do Sitio. a Região seria SP e nela precisamos criar os CEPs por bairros (sub-regiões).

A Default region originalmente é pra criar uma região completa pra ser usada em todo o mundo. SP precisa ser uma parte só. Funfa que nem o plugin dos Correios, vai sempre do mais abrangente pro mais restritivo.

O cliente está querendo inserir e não consegue. Vou pedir pra ela criar uma nova região e vemos como o site puxa o preço DEFAULT dela. Acontece que eles terão que recolocar todos os preços de produtos CERTO?

<img width="672" alt="screen shot 2016-07-11 at 15 14 02" src="https://cloud.githubusercontent.com/assets/5107285/16741639/9c351e98-477a-11e6-9956-785b83863a54.png">

**Comment by diogosp** [comment]
Pra Documentar:

Default Region não é a região de SP.
SP precisa estar criada separadamente com os CEPs editáveis
Porém os preços de SP devem ser duplicados na DEFAULT pro sistema funcionar
