### ISSUE TITLE
[Prioridade 3] Página "Como Funciona"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/aboaterra-theme#43]
Precisamos criar uma página que permita a inclusão do conteúdo neste formato:

![image](https://cloud.githubusercontent.com/assets/5949986/15615683/561f5d58-2405-11e6-84d6-39960c74c3cd.png)

Link (PSD): https://drive.google.com/drive/folders/0B8Nss0g77Q6cbW56TG9rX2FMYzA

Não sei se um Page Template é necessário nesse caso, ou se só aplicamos CSS para o texto e header e configuramos tudo via editor de texto. Veja o que acha mais interessante...

**Comment by matheusgimenez** [comment]
Feito.  A Página é um modelo chamado "Página Centralizada".

O formulário de CEP é um shortcode, nessa página pode ser utilizado com o seguinte codigo:

`[brasa_check_delivery label="CEP" container_width="300px"]`

Os titulos numerado são simples tags h1.

O botão de comprar é um shortcode gerado com o plugin da Brasa. Só escolher o tamanho grande e a cor laranja.

**Comment by diogosp** [comment]
@matheusgimenez  @LuwkasLima 
Testei as 4 coisas:

- [ X] Modelo de Página Centralizada

- [X ] Shortcode do CEP

- [ X] usar H1 pros títulos personalizados

- [ ] Botão comprar shortcode da Brasa. Não achei no editor isso. Está faltando algo no DEV?

**Comment by matheusgimenez** [comment]
Esqueci de ativar o plugin, fiz agora.

**Comment by LuwkasLima** [comment]
@diogosp eu ja havia feito essa pagina em Producao:

http://108.167.132.55/~aboat918/como-funciona/

So que nao usei o TEMPLATE que o @matheusgimenez criou, porque ele nao existia. Pega e muda o template da pagina em producao e coloca o shortcode, dai ta pronta...beleza?

**Comment by diogosp** [comment]
Lucas, Não sei se entendi o procedimento.


--


*Diogo Soares*
Brasa Design e Tecnologia - www.brasa.art.br <http://brasa.art.br/>
Tel.: (11)  3042-4475

Em 24 de junho de 2016 09:48, Lucas Lima <notifications@github.com>
escreveu:
