### ISSUE TITLE
Problema com PERMISSÃO da HOSPEDAGEM - erro deletar MENU e acessar PERSONALIZAR

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#45]
Pessoal,
To tendo um problema no HOSTGATOR que acho que é CONFIG do nosso WP - HTACCESS.

O Cliente criou um "menu" no WP. Foi um erro. Eu tento deletar (com user:Brasa). O Hostgator reclama que to proibido.
Já deu este erro pra mim quando no front-end eu clico no Personalizar. Quando to no backend ele entra normalmente.

<img width="914" alt="screen shot 2016-07-14 at 13 45 54" src="https://cloud.githubusercontent.com/assets/5107285/16847867/76e76abe-49c9-11e6-9ac0-f94de47a718f.png">

<img width="981" alt="403_-_forbidden" src="https://cloud.githubusercontent.com/assets/5107285/16847873/7e88dca8-49c9-11e6-869c-57484bf4fac6.png">

**Comment by LuwkasLima** [comment]
Ja tentou ver se eh acesso as pastas? 

 A configuração requisitada pelo WordPress é a "755".

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez 
1 - não tenho acesso a este servidor - quem instalou tudo por lá?
2 - quais pastas/arquivos devo procurar pra estes erros específicos?
3 - qual o impacto desta mudança na segurança e no DEV? Não sei reconhecer isso. Nem sei se é um erro que deveria estar acontecendo oras.

**Comment by diogosp** [comment]
@LuwkasLima @matheusgimenez achei a senha do cpanel.

- não achei nada fora dos 755 de permissão.
- o servidor ta reclamando que pode ser o .HTACCESS tb. Mas lá nao me arrisco a mexer.

**Comment by matheusgimenez** [comment]
Vou verificar isso hoje
