### ISSUE TITLE
Layout Página de Agradecimento - Página pós-finalizar compra

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#47]
É preciso fazer o CSS da página de Agradecimento. Número do Pedido.
MANTENHA O RESTANTE  DO TEMPLATE DO WOO (com o resumo). Só insira esta parte acima do layout mesmo

![2016-08-03_18h19_50](https://cloud.githubusercontent.com/assets/5107285/17382360/e064d0c0-59a6-11e6-8063-e9fbc1eb7493.png)

Link do PSD
https://drive.google.com/open?id=0B_zOFqExqtsKRnEyUWJkUDM1dTQ

**Comment by diogosp** [comment]
@matheusgimenez vou passar esta pro @isaquemelo tb.
Precisamos manter o resumo do pedido padrão do Woo pós-pagamento. E inserir este CSS aí em cima nos campos de Nº do pedido e inserir a frase.

**Comment by isaquemelo** [comment]
Aguardando estrutura do @matheusgimenez.

**Comment by diogosp** [comment]
@isaquemelo Esta estrutura já existe. o Matheus precisa te passar.
