### ISSUE TITLE
BLOG - Fazer layout

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#48]
Aplicar o layout da página nas postagens do BLOG

**Comment by diogosp** [comment]
@isaquemelo o que exatamente você fez neste ponto? (falha minha pq deveria ter dado mais referências pra sua execução).
Pq o blog continua o mesmo
http://dev.brasa.art.br/aboaterra/2016/05/02/post-do-blog-teste-1/
http://dev.brasa.art.br/aboaterra/2016/05/02/post-do-blog-teste-2/

E na real é só aplicar o layout (de fonte e título) que está nesta página aqui:
http://108.167.132.55/~aboat918/como-funciona/

**Comment by isaquemelo** [comment]
Tava fora do dev @diogosp.. Em relação a font do titulo eu preferi deixar a fonte padrão.. coloquei a do menu mas não fica nada **BOM** .

**Comment by diogosp** [comment]
@isaquemelo cara, realmente não é pra criarmos. siga isso aí que é o acordado com o cliente (pra evitarmos novos trampos em cima disso). Ele já aceitou isso e da forma como estamos é melhor não mexer

**Comment by isaquemelo** [comment]
OK.

**Comment by isaquemelo** [comment]
Não estou entendendo @diogosp..  Pq vc removeu o LABEL Para Revisão??

**Comment by diogosp** [comment]
Desculpe @isaquemelo não havia visto que vc atualizou.

**Comment by diogosp** [comment]
@isaquemelo duas correções aqui:

- Aumentar a fonte do CORPO DO TEXTO. deixar do tamanho que está o "Publicado em 2 de julho" abaixo do Título.

- Remover a data da postagem (verifica com o @matheusgimenez como faz isto)

![selection_006](https://cloud.githubusercontent.com/assets/5107285/18632550/5d593ea6-7e4e-11e6-9206-f2d81ac2e90b.png)
