### ISSUE TITLE
PENTE FINO GERAL >> Diminuir tudo conforme layout

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#49]
uma das questões mais faladas pela designer é que está tudo muito grande. enorme. sem espaços.
De uma maneira geral precisamos diminuir os blocos de todas as páginas (incluindo header e footer).
Não precisa ser EXATO ao layout, é só dar um espaço maior pros elementos

**Comment by isaquemelo** [comment]
O designer passou um layout em um tamanho gigantesco.. Mas seguindo pela lógica matemática o tamanho atual é o mais correto. Pois se aplicarmos uma regra de três simples teremos o seguinte:

2544 --- 1985 (tamanho do container em resolução de 2544px)
1366 --- x    (tamanho do container em telas comuns. Pelo qual será levado em consideração nos layouts de telas superiores)

2544x = 2711510
x = 2711510/2544= 1065px

**Comment by diogosp** [comment]
@isaquemelo BEM por aí! acho que ficou FINO (pelo menos na HOME). Vou tratar com o cliente

**Comment by diogosp** [comment]
@isaquemelo percebi que na Home desconfigurou os botões de + e - pra colocar no Carrinho. vc pode dar uma olhada nisso tb?

![2016-09-08_17h26_25](https://cloud.githubusercontent.com/assets/5107285/18365627/d8da6c70-75e9-11e6-9db2-910ea8c621b2.png)

**Comment by isaquemelo** [comment]
Tem certeza de que está com problemas? Aqui está normal(DEV e LOCAL). Checa o zoom do navegador.

**Comment by diogosp** [comment]
@isaquemelo Chequei... Em 2. Dá mais um espaçozinho pra caso a tela seja menor fique.mantido

**Comment by isaquemelo** [comment]
@diogosp Qual era o tamanho da tela quando ele quebrou?

**Comment by diogosp** [comment]
-   HEADER pode diminuir tudo uns 30% do que está.
-    A tipografia do menu pode diminuir uns 30%
-    O header todo precisa diminuir para caber o banner acima do fold como foi projetado, precisa apertar. Apertar onde estão as setas.

Destaques Abaixo do Banner Principal:
-    Diminuir os quadrados abaixo do banner como na imagem em anexo, cuidar pois as imagens estão sem resolução pois estão ampliadas.

![selection_013](https://cloud.githubusercontent.com/assets/5107285/18633442/b0601440-7e52-11e6-918c-2ed0842a4af1.png)

Veja as duas imagens sobrepostas: PSD e um print do site

![comparacao-sitio2](https://cloud.githubusercontent.com/assets/5107285/18633546/383c40d2-7e53-11e6-918c-745f2e047d82.png)
![comparacao-sitio1](https://cloud.githubusercontent.com/assets/5107285/18633545/3834de3c-7e53-11e6-8d64-d7f9fa1da8ac.png)



Retângulos dos Produtos:
-    Na área mais pedidos, está com os retângulos de tamanhos diferentes, deixa-los do mesmo tamanho sempre

-    Fresquinhos da horta, cuidar com o tamanho dos retângulos, estão de tamanhos diferentes, deixar do mesmo tamanho. A proporção dos produtos está desalinhado, por ex. O pimentao está enorme, deixar na proporção

![selection_012](https://cloud.githubusercontent.com/assets/5107285/18633396/88332e62-7e52-11e6-85b8-e16c50752015.png)

**Sei que estes quadros são moldáveis por conta do tamanho das Imagens inseridas nos produtos. mas em alguns lugares está quebrando demais isto**

**Comment by diogosp** [comment]
@isaquemelo diminuir os elementos da página de PRODUTO tb (single product). Reduzir título,, legenda, imagem - 10-15%

**Comment by isaquemelo** [comment]
Em relação ao tópico FRESQUINHOS DA HORTA não é possível verificar se a imagem está com a proporção correta. Isso o cliente tem que ver quando for colocar a imagem. Pq por exemplo se o cliente upar uma imagem com a proporção toda louca e outra com a proporção correta a regra irá se aplicar a ambos.

**Comment by isaquemelo** [comment]
Em relação ao tópico FRESQUINHOS DA HORTA não é possível verificar se a imagem está com a proporção correta. Isso o cliente tem que ver quando for colocar a imagem. Pq por exemplo se o cliente upar uma imagem com a proporção toda louca e outra com a proporção correta a regra irá se aplicar a ambos.

**Comment by diogosp** [comment]
@isaquemelo Entendido

**Comment by diogosp** [comment]
@isaquemelo preciso de mais uma ajeitada aqui.
O espaço entre as seções Mais Pedidos - Newsletter - Fresquinhos. Está muito largo. onde estão as setas pode juntar mais verticalmente. pra reduzir os espaços em branco. Mesma coisa entre os Fresquinhos e o BLOG. Entre blog e as frases e Instagram. Pode dar uma apertada.

![selection_020](https://cloud.githubusercontent.com/assets/5107285/18687780/05c49dd8-7f58-11e6-83e3-962089b47e10.png)
