### ISSUE TITLE
HOME >> seção Produtos mais vendidos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#5]
Nesta seção da Home puxa os produtos "Mais Vendidos". Apesar do título vamos puxar produtos "Destacados" por alguma taxonomia específica pra deixar mais aberto pra eles destacarem o que for melhor pra cada momento deles

<img width="798" alt="home_4_jpg" src="https://cloud.githubusercontent.com/assets/5107285/13110711/cc57b902-d568-11e5-90b6-9810189bf668.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
A edição desse item ficou na página Customizer (Personalizar).

Eu coloquei pra funcionar via tags de produto, é um seletor onde vai aparecer todas tags criadas.

**Comment by diogosp** [comment]
@matheusgimenez me explica este lance das TAGS no Customizer. Eu posso colocar várias separadas por vírgula?

**Comment by LuwkasLima** [comment]
@diogosp aqui eh a mesma situacao da issue #38 so que ao invez do Matheus utilizar Widgets ele utilizou o customizer.

@matheusgimenez acordamos que voce iria re-fazer ele pra ficar alinhado com a sessao "Fresquinhos da Nossa Horta" e portanto transforma-lo em Widget para que assim eles criem uma Tag chamada "Mais Pedidos" e possam colocar os produtos relacionados....

**Comment by matheusgimenez** [comment]
Feito. Lembrem de adicionar o widget de titulo e WC Query por Tags na area home email sidebar.

**Comment by LuwkasLima** [comment]
@matheusgimenez eu tive que incluir os Widgets dentro da area "Home E-mail Sidebar" porque se coloco na "Home Produtos Sidebar" ele joga a sessao "Mais Pedidos" para baixo da Newsletter.

![image](https://cloud.githubusercontent.com/assets/5949986/15403636/9de1723a-1dbf-11e6-9aba-a85f67f32dbf.png)

Vou marcar aqui pra um Pente-Fino, pra deixarmos isso mais fino..

**Pergunta:** Devo criar uma TAG pra "Mais pedidos" como no "Fresqueinhos da Nossa Horta"? Eu deixei vazio e apareceram alguns produtos, mas qual o criterio?

**Comment by LuwkasLima** [comment]
@matheusgimenez depois ve isso por gentileza? Obrigado! =)

**Comment by matheusgimenez** [comment]
Vão ser exibidos os ultimos produtos cadastrados ou os mais vendidos, existe opções no widget pra isso também.

**Comment by LuwkasLima** [comment]
Perfeito, obrigado!

**Comment by diogosp** [comment]
Precisamos fazer este pente fino. a seção no Widget ainda continua como **SIDEBAR E-MAIL** ta ruim de mostrar isso num tutorial pro cliente.... @matheusgimenez 

![2016-08-09_14h57_25](https://cloud.githubusercontent.com/assets/5107285/17527461/d265d9d4-5e41-11e6-91c3-c6fb86b60527.png)

**Comment by diogosp** [comment]
- Arrumar o editor de Widget conforme o @LuwkasLima apontou acima. O Editor está como EMAIL. Precisa ser pra Mais Pedidos
- CSS: diminuir os quadros dos produtos. estão grandes
- CSS: Centralizar o número de produtos pra pedir (estão na esquerda)

**Comment by diogosp** [comment]
@matheusgimenez veja a questão sobre o Widget estar desconfigurado (está na aba de EMAIL o lance pq o Lucas fez isto na pressa). Mas precisamos arrumar isto.

**Comment by matheusgimenez** [comment]
@diogosp @diogo, nao entendi esse

**Comment by diogosp** [comment]
@matheusgimenez A seção dos widgets que deveria ser Produtos Mais Vendidos, está como E-mail. Veja o print
