### ISSUE TITLE
Pente Fino - MOBILE

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#50]

**Comment by isaquemelo** [comment]
HOME, SINGLE PRODUCT, BLOG e CATEGORIA PRODUTO. Feitos. Não sei o que esta faltando.

**Comment by diogosp** [comment]
@isaquemelo aqui vão as definições para o MOBILE

- [ ] O site está flutuando para os lados, deveria ficar parado. (em várias páginas)

**Home** - modelo de base: [m.paodeacucar.com.br](url)

- o logo precisa ficar muito menor do que está, tipo 70% menor
- o carrinho ao lado do logo, sem info de quantidade. Centralizado pequeno.
-  Juntar no MENU HAMBURGER os DOIS menus do site. Loja em primeiro, depois o Institucional.
-  Banner Destaques Principal sobe bastante, fica na tela sem precisar de scroll.
-   O 3 quadrados abaixo do banner podem ficar um abaixo do outro - Estão como slider agora.
-   Footer: está todo quebrado precisa ficar legível e que dê para entender. Pode colocar uma informação abaixo da outra. Uma seção abaixo da outra.
- Não há necessidade de mini carrinho, vamos deixar mais simples, leva direto pro carrinho. Isto é, no desktop quando clica no carrinho no Header abre um resumo da compra. No Mobile vai direto pro carrinho.


**Produto**
- remover breadcrumb do mobile

**Minha Conta**
- Campos estão todos quebrados. Reajustar

**PAGINA DE CADASTRO**
-   O quero me cadastrar está fora do centro
-   Digitei meu email e diz que não foi encontrado, mas não abre o cadastro.
-   A tela do cep não reconhecido está com blocos sangrando precisa centralizar.

**Fluxo de Compra - Carrinho e Pagamento**

- coloquei continuar comprando e ele leva pra uma pagina que dá opção de cadastro - verificar se é um erro do mobile aparecer o restante do cadastro.
- quando vou preencher o formulário ele anda para a esquerda, ideal que fique parado.
- a linha endereço de email está quebrada, deixar somente "email"
- padronizar os verdes, o verde de entregar num novo endereço está diferente
- os boxes estão de tamanhos diferentes
- box "pagamento" está com um outro box cinza dentro do outline
- Campo de cartão, diminuir pontinhos dos cartões de crédito.
- fonte do preenchimento está bold, deixar normal.
- a opção que parece marcada é a de cartão de débito, como o default é credito preenchi "errado", e precisei repreecher tudo de novo no credito, melhor deixar as opção uma abaixo da outra e o usuario escolhe antes de colocar todos os dados.
- ao finalizar a compra caiu na home e precisei escrolar pra ver o agradecimento e perceber que havia dado certo a compra.

**Comment by isaquemelo** [comment]
Home - modelo de base: m.paodeacucar.com.br

- [ ] o logo precisa ficar muito menor do que está, tipo 70% menor
- [ ] o carrinho ao lado do logo, sem info de quantidade. Centralizado pequeno.
- [ ] Juntar no MENU HAMBURGER os DOIS menus do site. Loja em primeiro, depois o Institucional.
- [ ] Footer: está todo quebrado precisa ficar legível e que dê para entender. Pode colocar uma informação abaixo da outra. Uma seção abaixo da outra.



NÃO REALIZADOS:

- Banner Destaques Principal sobe bastante, fica na tela sem precisar de scroll: ISSO NÃO DEPENDE DO FRONT.. SE O CARA ACESSAR POR UMA TELA COM O HEIGHT MUITO PEQUENO NÃO TENHO COMO ESPREMER O CONTEUDO... O MAXIMO JÁ FOI FEITO NA ISSUE DE **DIMINUIÇÃO GERAL DO LAYOUT.**

- O 3 quadrados abaixo do banner podem ficar um abaixo do outro - Estão como slider agora: VER ISSO COM O @matheusgimenez.. NÃO SEI COMO FUNCIONA FOI FEITO COM O BRASA SLIDER.

- Não há necessidade de mini carrinho, vamos deixar mais simples, leva direto pro carrinho. Isto é, no desktop quando clica no carrinho no Header abre um resumo da compra. No Mobile vai direto pro carrinho. VAI ROLAR UM SCRIPT AÍ...

**Comment by isaquemelo** [comment]
Produto:

- [ ] remover breadcrumb do mobile


Minha Conta:

- [ ] Campos estão todos quebrados. Reajustar

PAGINA DE CADASTRO

- [ ] O quero me cadastrar está fora do centro
- [ ] Digitei meu email e diz que não foi encontrado, mas não abre o cadastro.
- [ ] A tela do cep não reconhecido está com blocos sangrando precisa centralizar.

**Comment by isaquemelo** [comment]
Fluxo de Compra - Carrinho e Pagamento

- [x] coloquei continuar comprando e ele leva pra uma pagina que dá opção de cadastro - verificar se é um erro do mobile aparecer o restante do cadastro: **Não constatei nenhum erro**
- [ ] quando vou preencher o formulário ele anda para a esquerda, ideal que fique parado.
- [ ] a linha endereço de email está quebrada, deixar somente "email"
- [ ] padronizar os verdes, o verde de entregar num novo endereço está diferente
- [ ] os boxes estão de tamanhos diferentes
- [ ] box "pagamento" está com um outro box cinza dentro do outline
- [ ] Campo de cartão, diminuir pontinhos dos cartões de crédito.
- [ ] fonte do preenchimento está bold, deixar normal.
- [ ] a opção que parece marcada é a de cartão de débito, como o default é credito preenchi "errado", e precisei repreecher tudo de novo no credito, melhor deixar as opção uma abaixo da outra e o usuario escolhe antes de colocar todos os dados.
- [ ] ao finalizar a compra caiu na home e precisei escrolar pra ver o agradecimento e perceber que havia dado certo a compra.

**Comment by diogosp** [comment]
@matheusgimenez temos duas pendências que precisamos de ajuda no MOBILE

- O 3 quadrados (que são slider brasa tb) abaixo do banner principal podem ficar um abaixo do outro - Estão como slider agora.
<img width="295" alt="screen shot 2016-12-16 at 12 44 06" src="https://cloud.githubusercontent.com/assets/5107285/21266433/5e49d314-c38d-11e6-9dfc-0ca6dd62b1e0.png">



- Não há necessidade de mini carrinho no Mobile, vamos deixar mais simples, leva direto pro carrinho. Isto é, no desktop quando clica no carrinho no Header abre um resumo da compra. No Mobile vai direto pro carrinho. 
<img width="692" alt="screen_shot_2016-12-16_at_12_43_20" src="https://cloud.githubusercontent.com/assets/5107285/21266420/4d9cb89c-c38d-11e6-8a66-57b86172214a.png">

**Comment by diogosp** [comment]
@matheusgimenez 
Mini Cart OK. resolvido.

Mas os 3 blocos que eram slider agora sumiram. Não aparecem no Mobile, nem como slider, nem como blocos
