### ISSUE TITLE
Remover Menu da Loja em algumas páginas

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#53]
![selection_014](https://cloud.githubusercontent.com/assets/5107285/18645425/8230d9a2-7e83-11e6-9bae-dec9676d407e.png). 

*Agradecimento

*Cadastro

*CEP não Atendido

*Meu Carrinho

**Comment by matheusgimenez** [comment]
Feito. No Dev

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo 
- Precisamos ajustar o espaçamento depois da remoção do Menu. Aumentar o espaço entre o título da página em o LOGO principal. Ficou tudo muito junto.

<img width="1272" alt="carrinho_ _a_boa_terra" src="https://cloud.githubusercontent.com/assets/5107285/19537688/b577057a-962f-11e6-9ed3-0f16895d7b24.png">

- Remover o menu da Loja da página de PAGAMENTO tb.

**Comment by isaquemelo** [comment]
Front-end fechado.

**Comment by diogosp** [comment]
@matheusgimenez precisamos aumentar um pouco mais o espaçamento entre o logo e o título das páginas que ficaram sem o menu. 

*Agradecimento
*Cadastro
*CEP não Atendido
*Meu Carrinho
* Pagamento

**Comment by diogosp** [comment]
@matheusgimenez teve alguma alteração mesmo? será que subiu pro DEV? não consegui ver diferença
