### ISSUE TITLE
BUG - Inserir Cupom altera valor CART

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#55]
Segue as telas do erro.
Tela 1 - Cliente vai pro carrinho com o total X
Tela 2 - Insere o cupom e o valor do carrinho altera.

![image001](https://cloud.githubusercontent.com/assets/5107285/20003542/32639b6c-a26e-11e6-8890-d0dbbba2b1c7.png)

![image002](https://cloud.githubusercontent.com/assets/5107285/20003558/48eac252-a26e-11e6-9568-c6632fa90f1f.png)

**Comment by matheusgimenez** [comment]
Hoje consegui chegar no seguinte:

O valor do desconto feito quando existe produto do tipo bundle no cart (desconto automatico removendo o valor de cada item do bundle) quando há cupom está fazendo o calculo errado. Hoje, então, consegui chegar na causa, preciso resolver ainda.
