### ISSUE TITLE
Criar botão no CART - "Esvaziar Carrinho"

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#57]
O carrinho deles é por muitas vezes abandonado. E como a cada semana as Cestas mudam eles querem que o cliente tenha uma opção simples de esvaziar tudo.

Inserir na página do CARRINHO (CART) acima do **Continuar Comprando** um botão "Esvaziar Carrinho" com a função de remover todos os produtos já inseridos anteriormente.

**Comment by matheusgimenez** [comment]
Feito. Está no DEV

**Comment by diogosp** [comment]
@matheusgimenez 
- ao clicar em esvaziar carrinho o usuário é redirecionado pra Home. É este o comportamento que você planejou mesmo?

**Comment by diogosp** [comment]
@matheusgimenez você acha que este botão deveria ter uma confirmação de execução? tipo um "você realmente deseja esvaziar completamente o carrinho?"

**Comment by matheusgimenez** [comment]
@diogosp pensei nisso tbm.. um confirm box simples mesmo? exemplo: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm (clica em try it)

**Comment by diogosp** [comment]
@matheusgimenez é exatamente isso. pode rodar!

**Comment by matheusgimenez** [comment]
@diogosp Feito! Esta no dev!

**Comment by matheusgimenez** [comment]
@diogosp 

No box de confirmação eu tinha deixado a seguinte mensagem: "Você realmente deseja esvaziar completamente o carrinho?"
Mas to achando que não ficou legal pelo seguinte motivo:

O botão de confirmar é o "OK". Não é possível alterar o nome dos botões do confirm box do navegador. E acho que a frase em si não ta deixando claro que pra pessoa deletar o carrinho precisa clicar no OK.

Pensei em algo como: "Você realmente deseja esvaziar completamente o carrinho? Clique em OK para esvaziar." Algo assim..

Pode me ajudar com isso?

**Comment by diogosp** [comment]
Eu deixaria bem simples. Eu acho que é redundante o esvaziar/completamente....

**"Esvaziar carrinho. Confirma?"**
Ou até colocaria, "esta ação não pode ser desfeita"

**Comment by LuwkasLima** [comment]
"Clique em OK para esvaziar o carrinho de compras e retornar".

O que acham?

**Comment by matheusgimenez** [comment]
Quando o carrinho é atualizado via AJAX o botão está perdendo a referencia no DOM e assim não está executando o confirm box. 

Preciso usar o .on() do jQuery através de uma tag pai carregada no load.

Traduzindo para não tecnicos:

Depois de carregar via AJAX, se você clica em Esvaziar Carrinho, ele esvazia sem abrir o box de confirmação.

**Comment by matheusgimenez** [comment]
Corrigido e enviado para todos ambientes.

**Comment by LuwkasLima** [comment]
@diogosp fechamos esse?

**Comment by diogosp** [comment]
@LuwkasLima Sim!
