### ISSUE TITLE
Alterar layout Pagamento - Cartão de Crédito e Débito aparecerem com os campos Fechados

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#58]
Ao clicar no tipo de pagamento (débito ou crédito) é que se expandem os campos para preenchimento dos dados. Com os campos abertos o cliente está ficando confuso se é débito ou crédito que está sendo aplicado. O foco é melhorar a usabilidade e deixar mais claro pro usuário qual a opção de pagamento.

<img width="1188" alt="finalizar_compra_ _a_boa_terra" src="https://cloud.githubusercontent.com/assets/5107285/23560174/4a9e1c68-0018-11e7-8212-e99b588e6bd2.png">

**Comment by LuwkasLima** [comment]
@diogosp: Vc sabe dizer se o campo eh igual para os 2 modos de pagamento? Muda alguma coisa entre um e outro (eu nao lembro como é no BR mais...). Pergunto isso pq poderíamos deixar como um campo ja aberto e um dos campos eh um dropdown com a opcao Debito/Credito.

Seria bom tbm dar uma pesquisada em outras lojas pra ver como elea fazem. De qualquer maneira, tem que ver como o @matheusgimenez pensou isso quando estimou as horas de trabalho.

**Comment by diogosp** [comment]
Lucas,
Eles querem todos os campos fechados. ponto. Pq os clientes estão se confundindo por conta exatamente dos campos serem idênticos. O usuário precisa passar primeiro por esta seleção de DéBito ou Crédito para aí sim inserir os dados. Isto dará mais segurança de que a pessoa realmente viu a opção que escolheu.

**Comment by matheusgimenez** [comment]
Enviei para o DEV esse. Pode revisar já!
