### ISSUE TITLE
Bug - Erro login insere produto no carrinho

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#60]
@matheusgimenez queria que você revisasse uma questão, que não sei se veio das mudanças pra estas Novas Demandas.

Mesmo dando erro no login (tipo insere senha errada) o produto está sendo colocado no CART sem o login efetivo do usuário. Isto é um erro do fluxo (pq precisamos testar o CEP da pessoa efetivamente).

@LuwkasLima queria que você acompanhasse aqui. Não sei de onde vem este erro se foi por conta das novas mudanças... mas e se for erro antigo e deixamos passar? Como consertamos isso dentro do fluxo de trampo nosso?

**Comment by LuwkasLima** [comment]
@diogosp eu entendo que essa discussao foi feita antes e provavelmente existe uma Issue que explica a situacao. Se voce puder compartilhar um cenario que mostra o problema, podemos avaliar se (1) isso foi vacilo nosso durante o desenvolvimento ou se (2) foi alguma mudanca requisitada pelo cliente que pode ter resultado nesse "problema". 

(1) deveria ser tratado como de responsabilidade nossa
(2) deveria ser discutido com o cliente para que seja alocado horas para re-design das duas solucoes propostas pra que elas nao conflitem.

Pra podermos fazer isso, precisamos de um cenario (passo a passo) onde o problema ocorre.

**Comment by diogosp** [comment]
reproduzir erro:

- entra no site. tenta inserir algo no carrinho.
- abre o modal pra logar
- coloca qq e-mail ou senha. volta pra Home. PORÉM ele insere o produtor no carrinho de qq maneira.

Foi isso que expliquei anteriormente.
