### ISSUE TITLE
Home >> últimos posts do Blog

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#7]
Nesta seção puxa os 3 últimos posts do blog da Boa Terra.

<img width="858" alt="home_4_jpg" src="https://cloud.githubusercontent.com/assets/5107285/13110971/4f9493c0-d56a-11e5-88d8-28d05c16c13e.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Resolvi criando um novo widget chamado "Últimas do Blog".

**Comment by diogosp** [comment]
Ficou lindo.

**Comment by diogosp** [comment]
- CSS. Diminuir os blocos dos posts na HOME. estão grandes.

**Comment by diogosp** [comment]
@isaquemelo PENTE FINO.

- Deixar o resumo do texto JUSTIFICADO
- Alinhar os títulos pelo tamanho de duas linhas - como no exemplo só tem título de 1 linha ele quebra e empurra o texto pra baixo.

![selection_015](https://cloud.githubusercontent.com/assets/5107285/18645874/67a1b60e-7e85-11e6-9946-e29051998922.png)

**Comment by diogosp** [comment]
@isaquemelo este aqui entrou no sprint?

**Comment by isaquemelo** [comment]
Ixxxi esqueci... perae em 5min faço.

**Comment by isaquemelo** [comment]
Tudo feito só não a pate das linhas. Não entendi.

**Comment by diogosp** [comment]
@isaquemelo conseguiu mexer aqui? não está justificado nem alinhado o título ainda.

**Comment by isaquemelo** [comment]
Eu fiz a parte da justificação e a redução da fonte(esqueci de upar). Mas esse negocio das linhas não sei como irei fazer... Estou sem ideia.. da uma luz @matheusgimenez

**Comment by isaquemelo** [comment]
@isaquemelo Já achei uma solução.

**Comment by diogosp** [comment]
@isaquemelo Aproveita e diminui um pouco o tamanho do resumo do post. A fonte

**Comment by isaquemelo** [comment]
Tudo feito. No DEV.
