### ISSUE TITLE
Home >> Seção de Frases e Pensamentos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#8]
Eles querem esta seção para colocar frases e pensamentos simples em texto. No máximo uns 3-4 pensamentos rotativos

<img width="875" alt="home_4_jpg" src="https://cloud.githubusercontent.com/assets/5107285/13111035/ab8f3b76-d56a-11e5-8fee-f63df2ca86dc.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by matheusgimenez** [comment]
Resolvi esse utilizando o seguinte plugin:

https://wordpress.org/plugins/testimonialslider/

Já temos uma area de widget ali, então é só chamar o shortcode dele num widget de texto.

**Comment by diogosp** [comment]
@matheusgimenez acho que precisa de um pente fino no espaçamento com a seção de baixo. Achei que precisa de mais respiro.

**Comment by LuwkasLima** [comment]
Concordo com o @diogosp , veja os espacos:

![image](https://cloud.githubusercontent.com/assets/5949986/15194325/05d93b18-1788-11e6-932a-2e6b4f999b26.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Perrfeito @matheusgimenez !

**Comment by diogosp** [comment]
Pente Fino CSS

- Setas estão desformatadas
- texto precisa ser mais leve (como na primeira frase) como padrão

**Comment by diogosp** [comment]
@isaquemelo as setas ainda estão quebradas no meu navegador. pode deixar ela mais fina e menor.

<img width="1374" alt="a_boa_terra_ _organicos" src="https://cloud.githubusercontent.com/assets/5107285/18071061/00c0b60e-6e29-11e6-9cdc-011b101b5cbc.png">

**Comment by isaquemelo** [comment]
Foi mal mano.. esqueci de commitar.. Vai agora..
