### ISSUE TITLE
HOME >> Seção Instagram

### ISSUE THREAD

**Issue by diogosp** [brasadesign/aboaterra-theme#9]
Aqui precisa puxar uma galeria do Instagram deles
Vi que existem vários plugins que fazem isso. Peguei os dois mais votados:

[Enjoy](https://wordpress.org/plugins/enjoy-instagram-instagram-responsive-images-gallery-and-carousel/)

[Alpine](https://wordpress.org/plugins/alpine-photo-tile-for-instagram/)

<img width="864" alt="home_4_jpg" src="https://cloud.githubusercontent.com/assets/5107285/13111086/f9047d76-d56a-11e5-9bee-a6349f38e0b6.png">

Link para a Home completa
https://drive.google.com/open?id=0B_zOFqExqtsKeURUQ09TMzFfVGs

**Comment by diogosp** [comment]
Ahhh eu já havia linkado aqui na Issue (veja duas opções lá em cima) mas repito:

https://wordpress.org/plugins/enjoy-instagram-instagram-responsive-images-gallery-and-carousel/

**Comment by matheusgimenez** [comment]
Feito

**Comment by diogosp** [comment]
@matheusgimenez as setas de praticamente toda a Home estão vazando nos cantos da janela (incluíndo aqui o Instagram).

**Comment by LuwkasLima** [comment]
@matheusgimenez adiciono aqui a necessidade de buscarmos uma solução para as imagens, infelizmente não está nem um pouco amigável. Talvez, para essa primeira entrega, se diminuirmos o tamanho das imagens, será que fica um pouco melhor?

![image](https://cloud.githubusercontent.com/assets/5949986/15194243/9772a8e4-1787-11e6-8dda-ebe03cf63acf.png)

**Comment by matheusgimenez** [comment]
Fiz um fork do plugin corrigindo o tamanho, segue:

https://github.com/brasadesign/instagram-widget-wp

**Comment by matheusgimenez** [comment]
Subi pro Dev

**Comment by LuwkasLima** [comment]
Ficou muito melhor @matheusgimenez certinho!

**Comment by diogosp** [comment]
@matheusgimenez o plugin do Instagram não está se autenticando com o site do Instagram. Dá um erro. talvez pq o plugin esteja desatualizado. vai saber.

**Comment by diogosp** [comment]
@matheusgimenez na Home está puxando as fotos do Instagram com uma resolução muito baixa. É confguração? é limitação do plugin?

**Comment by matheusgimenez** [comment]
@diogosp Eh o plugin que ta zoado. Eu tinha feito uma modificaçao pra corrigir o tamanho das imagens, mas como vc atualizou, sobrepos, mas to subindo de novo

**Comment by diogosp** [comment]
@matheusgimenez valeu. resolvido
